### ISSUE TITLE
[koffi] I want to implement mouse and keyboard hook.

### ISSUE THREAD

**Issue by arkmore** [Koromix/koffi#1]
I can't speak English well. Please understand.

Using the mouse and keyboard hook using node-ffi-napi.

Below is my example code.

const keyboardProc = ffi.Callback(LRESULT, [INT, WPARAM, KBDLLHOOKSTRUCT], (nCode, wParam, lParam) => {
	... 	
	return user32.CallNextHookEx(hHookKeyboard, nCode, wParam, lParam));
});
hHookKeyboard = user32.SetWindowsHookExW(WH_KEYBOARD_LL, keyboardProc, 0, 0);
user32.UnhookWindowsHookEx(hHookKeyboard);

How can I implement the same using koffi?

**Comment by NotYoojun** [comment]
Hi, is there an answer to this? or tutotials I can refer to? Thks
