### ISSUE TITLE
Error using browserify to bring koffi on browser

### ISSUE THREAD

**Issue by pierluromani** [Koromix/koffi#100]
Hi, I'm using a node library (brainflow, found here [https://github.com/brainflow-dev/brainflow](url)) that has koffi in its dependencies. I'm trying to bring it on the browser by using browserify ([https://github.com/browserify/browserify](url)) but I get this error in the browser's console:
`Uncaught Error: Project koffi does not support the Node NaN.x branch (N-API < 8)`

What could be the reason? Is there a way to solve this?

**Comment by Koromix** [comment]
Node.js FFI libraries cannot be used inside the browser. Koffi is meant to help you use native shared libraries from Node.js.

You can't ask the OS to load a native shared library or call anything in it form inside the browser.
