### ISSUE TITLE
How to write this code using koffi?

### ISSUE THREAD

**Issue by matheusgomesbs** [Koromix/koffi#103]
```Javascript 
const ffi = require('ffi-napi');
const ref = require('ref-napi')

let logging ;
const buffLength = 256;

let aloc_sResponse = Buffer.alloc(buffLength);
let aloc_esLength = ref.alloc('int', buffLength);

logging = libm.getLastResponse(aloc_sResponse, aloc_esLength );
console.log(logging);
console.log('message: ', aloc_sResponse.toString());
```

basically the value of the variable `aloc_sResponse` will be filled by the return of the function itself.

Sorry for bad English :/

**Comment by Koromix** [comment]
Not sure how is getLastResponse defined, but I guess it should be something like this:

```js
const koffi = require('koffi');

const libm = koffi.load('libm.so');
const getLastResponse = libm.func('int getLastResponse(_Out_ void *buf, _Inout_ int *bufLength)');

const bufLength = 256;

let aloc_sResponse = Buffer.alloc(bufLength);
let aloc_esLength = [buf.length];

let logging = getLastResponse(aloc_sResponse, aloc_esLength);

console.log(logging);
console.log('length: ', aloc_esLength[0]);
console.log('message: ', aloc_sResponse.toString());
```

**Comment by matheusgomesbs** [comment]
sorry, Sorry, the `getLastResponse()` is defined like this: 
```Javascript
const getLastResponse = lib.func('NFE_StatusServico', 'int', ['string', 'int']);
 ```
The String with predefined length so that it can be filled with the return value

**Comment by matheusgomesbs** [comment]
> Not sure how `getLastResponse()` is defined, but I guess it should be something like this:
> 
> ```js
> const koffi = require('koffi');
> 
> const libm = koffi.load('libm.so');
> const getLastResponse = libm.func('int getLastResponse(_Out_ void *buf, _Inout_ int *bufLength)');
> 
> const bufLength = 256;
> 
> let aloc_sResponse = Buffer.alloc(bufLength);
> let aloc_esLength = [buf.length];
> 
> let logging = getLastResponse(aloc_sResponse, aloc_esLength);
> 
> console.log(logging);
> console.log('length: ', aloc_esLength[0]);
> console.log('message: ', aloc_sResponse.toString());
> ```

This code is executed however the variable `aloc_sResponse` is not filled by the function return. Buffer returns empty

**Comment by matheusgomesbs** [comment]
I managed to make it work using the `ref-napi` library. The code looked like this:

```Javascript
import ref from "ref-napi"
import koffi from "koffi";

const lib = koffi.load('myLib64.dll');

const getLastResponse = lib.func('NFE_StatusServico', 'int', ['_Out_ str *buf', '_Inout_ int *buffLength']);
const buffLength = 300;
const aloc_sResponse = Buffer.alloc(buffLength)
const aloc_esLength = ref.alloc('int', buffLength);

let logging = getLastResponse(aloc_sResponse, aloc_esLength);

console.log(logging , '=>', aloc_sResponse.toString())

```

**Comment by Koromix** [comment]
My code was not even correct because it was using an undefined variable so that might not have helped :)

This should work without ref-napi:

```js
import koffi from "koffi";

const lib = koffi.load('myLib64.dll');

const getLastResponse = lib.func('NFE_StatusServico', 'int', ['_Out_ str *buf', '_Inout_ int *buffLength']);
const buffLength = 300;
const aloc_sResponse = Buffer.alloc(buffLength)
const aloc_esLength = [buffLength];

let logging = getLastResponse(aloc_sResponse, aloc_esLength);

console.log(logging , '=>', aloc_sResponse.toString())
```

Some documentation about pointers and output parameters in Koffi:

- https://koffi.dev/pointers#pointer-to-primitive-types
- https://koffi.dev/output#primitive-value

**Comment by matheusgomesbs** [comment]
It worked perfectly without `ref-napi`. Thank you for your support.
