### ISSUE TITLE
unable to pass a pointer as element of a struct/buffer

### ISSUE THREAD

**Issue by sfrieske** [Koromix/koffi#104]
in a struct like
`typedef struct I2C_rdwr_ioctl_data {`
`    i2c_msg *msgs;    /* pointer to i2c_msgs */`
`   uint32_t nmsgs;    /* number of i2c_msgs */`
`} i2c_rdwr_ioctl_data;`
i2c_msg is a pointer to a JS Uint8Array or the like. 
The function to obtain this pointer is either missing or not (well enough) documented.

**Comment by Koromix** [comment]
Can you be more specific?

Here is example that uses ioctl for i2c, according to Linux documentation. I don't have any i2c device so I could not test it fully.

```js
const koffi = require('koffi');

const libc = koffi.load('libc.so.6');

const open = libc.func('int open(const char *path, int flags, unsigned int mode)');
const close = libc.func('int close(int fd)');
const ioctl = libc.func('int ioctl(int fd, unsigned long request, ...)');
const O_RDWR = 02;
const O_CLOEXEC = 02000000;

const i2c_msg = koffi.struct('i2c_msg', {
    addr: 'uint16_t',
    flags: 'uint16_t',
    len: 'uint16_t',
    buf: 'uint8_t *'
});
const I2C_rdwr_ioctl_data = koffi.struct('I2C_rdwr_ioctl_data', {
    msgs: 'i2c_msg *',
    nmsgs: 'uint32_t'
});
const I2C_RDWR = 0x0707;

let fd = open('/dev/i2c-1', O_RDWR | O_CLOEXEC, 0);
if (fd < 0)
    throw new Error('Failed to open I2C device');

try {
    let msgs = [
        { addr: 0, flags: 0, len: 8, buf: Buffer.alloc(8) },
        { addr: 42, flags: 24, len: 512, buf: Buffer.alloc(512) }
    ];
    let data = {
        msgs: msgs,
        nmsgs: msgs.length
    };

    // For vararg functions, see here: https://koffi.dev/functions#variadic-functions
    let ret = ioctl(fd, I2C_RDWR, 'I2C_rdwr_ioctl_data *', data);
    console.log(ret);

    // ...
} finally {
    close(fd);
}
```

**Comment by sfrieske** [comment]
Thanks for your reply, including the detailed code! `koffi.struct` is obviouslyKoffi's elegant way to handle the specific problem in my post.
Coming from other FFI implementaions for JS, going a bottom up way, I have no `koffi.struct('i2c_msg', ...)` but a plain Uint8Array or Buffer instead. How would the pointer to this be obtained - like `koffi.pointer(Buffer.alloc(8))`?

**Comment by Koromix** [comment]
Just set the member to the buffer :)

```js
const I2C_rdwr_ioctl_data = koffi.struct('I2C_rdwr_ioctl_data', {
    msgs: 'i2c_msg *',
    nmsgs: 'uint32_t'
});

let count = 8;
let buf = Buffer.alloc(count * 16);

// Fill the buffer somehow

let data = {
    msgs: buf,
    nmsgs: count
};

let ret = ioctl(fd, I2C_RDWR, 'I2C_rdwr_ioctl_data *', data);
console.log(ret);
```

**Comment by sfrieske** [comment]
This is the solution I was looking for. Thanks a lot!
Once you come across the docs: this might become another instructive showcase for the use of pointers.
Closing this issue.
