### ISSUE TITLE
how to call EnumWindows?

### ISSUE THREAD

**Issue by jbeetle** [Koromix/koffi#105]
i want to call EnumWindows
  const EnumWindows= lib.stdcall('EnumWindows', 'bool', ['uint','int']);
    EnumWindows((hwnd, param)=>{
        console.log(hwnd,param);
    },10);
but it don't work ,how?

**Comment by Koromix** [comment]
Like this:

```js
const koffi = require('koffi');

const user32 = koffi.load('user32.dll');

const WNDENUMPROC = koffi.proto('bool __stdcall WNDENUMPROC(void *hwnd, intptr_t lparam)');
const EnumWindows = user32.func('bool EnumWindows(WNDENUMPROC *func, intptr_t lparam)');

EnumWindows((hwnd, lparam) => {
    // To get the decoded/plain value of hwnd, which is a pointer, use koffi.address(hwnd)
    console.log(hwnd, lparam);
    return true;
}, 100);
```

**Comment by jbeetle** [comment]
> Like this:
> 
> ```js
> const koffi = require('koffi');
> 
> const user32 = koffi.load('user32.dll');
> 
> const WNDENUMPROC = koffi.proto('bool __stdcall WNDENUMPROC(void *hwnd, intptr_t lparam)');
> const EnumWindows = user32.func('bool EnumWindows(WNDENUMPROC *func, intptr_t lparam)');
> 
> EnumWindows((hwnd, lparam) => {
>     // To get the decoded/plain value of hwnd, which is a pointer, use koffi.address(hwnd)
>     console.log(hwnd, lparam);
>     return true;
> }, 100);
> ```

it's great，thank you!
