### ISSUE TITLE
error reported mac system

### ISSUE THREAD

**Issue by taozhupipi** [Koromix/koffi#107]
electron project 
koffi -v 2.6.6
when i run it...

Error: Project koffi requires Node >= 14.17.0 in the Node 14.x branch (N-API >= 8)
                                    
mac@MacdeMac-mini aipaintking % node -v
v14.17.0

mac@MacdeMac-mini aipaintking % node -p "process.versions"
{
  node: '14.17.0',
  v8: '8.4.371.23-node.63',
  uv: '1.41.0',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.17.1',
  modules: '83',
  nghttp2: '1.42.0',
  napi: '8',
  llhttp: '2.1.3',
  openssl: '1.1.1k',
  cldr: '38.1',
  icu: '68.2',
  tz: '2020d',
  unicode: '13.0'
}
mac@MacdeMac-mini aipaintking % nvm list
->     v14.17.0
       v16.14.0

change node version also reported err

**Comment by Koromix** [comment]
Node might be recent enough, but when you use electron it's another build of the V8 JS engine that is used.
Use a more recent Electron version, and that should do it.
