### ISSUE TITLE
How to return pointer value from JavaScript to C in JavaScript callbacks

### ISSUE THREAD

**Issue by wanglin86769** [Koromix/koffi#114]
Hello,
 
I want to use koffi to call EPICS Portable Channel Access Server shared library, and most of the logic are already in the shared library. However, I want to keep a read and a write callbacks in JavaScript for customization purpose, and the two callbacks will be called by the shared library when events happen.

The C definition of the two callbacks are as follows, ReadCallback is used to read data from JS to C, while WriteCallback is used to write data from C to JS. The data can be of any type and scalar/array, so it is defined as void*.
```
typedef void (*ReadCallback)(char*, void*);
typedef void (*WriteCallback)(char*, void*);
```

The JS definition is as follows, for WriteCallback, the value passed from C to JS can be decoded with koffi.decode(). However, I cannot figure out how to return data from JS to C in ReadCallback, which means using the following code snippet in ReadCallback to return a float pointer from JavaScript to C does not work.
```
let readCallbackPtr = koffi.register((reason, result) => {
    result = koffi.as([100.123], 'float *');
}, koffi.pointer(ReadCallback));

let writeCallbackPtr = koffi.register((reason, value) => {
    console.log(koffi.decode(value, 'float'));
}, koffi.pointer(WriteCallback));
```

**Comment by Koromix** [comment]
It works but it is kinda slower than it needs to be, because:

- Koffi encodes the floats to scratch memory
- Koffi calls memcpy (which involves checking and converting call arguments, calling memcpy on alternate call stack, etc.), just to copy the encoded float array as-is

This will result in faster performance (less steps, the values are encoded directly in the memory pointed by the `result` pointer):

```js
let readCallbackPtr = koffi.register((reason, result) => {
    let values = [10.11, 10.22, 10.33];
    koffi.encode(result, 'float *', values);
}, koffi.pointer(ReadCallback));
```

**Comment by Koromix** [comment]
You're right, I got it wrong.

For `typedef void (*ReadCallback)(char*, void*);` you can use this:

```js
let readCallbackPtr = koffi.register((reason, result) => {
    let values = [10.11, 10.22, 10.33];
    koffi.encode(result, koffi.array('float', values.length), values);
}, koffi.pointer(ReadCallback));
```

**Comment by Koromix** [comment]
With Koffi 2.6.11 (which I've just released), you can also do this (as documented here: https://koffi.dev/variables#encode-to-c-memory):

```js
let readCallbackPtr = koffi.register((reason, result) => {
    let values = [10.11, 10.22, 10.33];
    koffi.encode(result, 'float', values, values.length);
}, koffi.pointer(ReadCallback));
```

This form should have worked with Koffi < 2.6.11 but it was broken (and undocumented anyway) 😅

**Comment by wanglin86769** [comment]
Thanks for releasing the new version, it works,

In addition, for the fixed-width string array, which for example defines `char* str` and uses `str + 0` for the first element, `str + 40` for the second element, `str + 80` for the third element, the following code snippet also works for me.

```
const MAX_STRING_SIZE = 40;
let readCallbackPtr = koffi.register((reason, result) => {
    let values = ['abc', 'def', 'xyz', 'aaaaaa', 'bbbbbb', 'cccccc'];
    for(let i = 0; i< values.length; i++) {
        let value = values[i];
        koffi.encode(result, MAX_STRING_SIZE * i, 'char', value, value.length + 1);
    }
}, koffi.pointer(ReadCallback));
```
