### ISSUE TITLE
Koffi memory access violation on x86 only

### ISSUE THREAD

**Issue by Elendiar** [Koromix/koffi#116]
Hello, after porting my app from ref-napi to koffi I encountered a problem in the ia_32 build.

Sample code that works in x64, but does not work in x86:
```JS
import koffi from "koffi";

const HANDLE = koffi.pointer(koffi.opaque("HANDLE"));
const HWND = koffi.alias("HWND", HANDLE);

const user32 = koffi.load("User32.dll");

// BOOL CALLBACK EnumWindowsProc(
//     _In_ HWND   hwnd,
//     _In_ LPARAM lParam
//   );
const EnumWindowsProc = koffi.proto("EnumWindowsProc", koffi.types.bool, [
  HWND,
  koffi.types.long,
]);
// BOOL EnumWindows(
//     [in] WNDENUMPROC lpEnumFunc,  -> A pointer to an application-defined callback function
//     [in] LPARAM      lParam
//   );
const enumWindows = user32.stdcall("EnumWindows", koffi.types.bool, [
  koffi.pointer(EnumWindowsProc),
  koffi.types.long,
]);

const windowsProc = koffi.register((hwnd, lParam) => {
  console.log("hwnd", hwnd, "lParam", lParam, Number(koffi.address(hwnd)));
  return true; // continue enumerate
}, koffi.pointer(EnumWindowsProc));

console.log("start enumerate");
enumWindows(windowsProc, 0);
console.log("end enumerate");

```
In x64 all fine, printed "end enumerate" from console log. In x86 environment (on in x86 build runned on x64 os) process crashes without error before reaching "end enumerate".
 In application calling `enumWindows` on x86 arch causes an error:
```PLAIN
0xc0000005: The thread tried to read from or write to a virtual address for which it does not have the appropriate access.

Unhandled exception at 0x6CE44642 (koffi.node) in 2adef64c-0bad-41de-8767-a16b0153c494.dmp: 0xC0000005: Access violation writing location 0x000717C2.

[Inline Frame] taskbar-client.exe!ShimMalloc(unsigned int size=1153942365, void * context)

```

But its partially works - enumarate few windows, but at some point it crashes.

UPDATED: 
This [comment ](https://github.com/Koromix/koffi/issues/93#issuecomment-1768415454) prompted me to try using prototype syntax and it worked! But i dont understand what difference between
```JS
const EnumWindowsProc = koffi.proto('bool __stdcall EnumWindowsProc (HWND hwnd, long lParam)');   // this works!
```
and 
```JS
const EnumWindowsProc = koffi.proto("EnumWindowsProc", koffi.types.bool, [HWND, koffi.types.long]);   // this crashes
```
and how it make work with classic node-ffi syntax?

**Comment by Koromix** [comment]
The Windows API uses the __stdcall calling convention on 32-bit platforms, for functions and for callbacks. On other platforms, there is only one convention (well, Windows x64 has __vectorcall but Koffi does not support it ATM), so it's ignored.

Although it's good style, it does not really matter if you specify __stdcall or not for function calls. It works regardless. However, for callbacks, it must be correct or the code will crash.

However, it was indeed a limitation of Koffi, that you could not specify the calling convention for callbacks with the classic syntax. I've changed this in Koffi 2.7, which I've just published.

Upgrade to Koffi 2.7 to use this syntax:

```js
const EnumWindowsProc = koffi.proto( '__stdcall', 'EnumWindowsProc', koffi.types.bool, [HWND, koffi.types.long]);
```

For consistency, I've also changed how you are supposed to declare stdcall/fastcall/thiscall functions:

```js
// Before:
const MessageBoxA = lib.stdcall('MessageBoxA', 'int', ['void *', 'str', 'str', 'uint']);

// After:
const MessageBoxA = lib.func('__stdcall', 'MessageBoxA', 'int', ['void *', 'str', 'str', 'uint']);
```

The old away is still supported but deprecated, and will be removed in Koffi 3.0.

Documentation here: https://koffi.dev/callbacks#callback-types
