### ISSUE TITLE
`koffi.pointer`'s third argument should be typed as optional in `index.d.ts`

### ISSUE THREAD

**Issue by tamuratak** [Koromix/koffi#118]
To my understanding, `koffi.pointer`'s third argument, `asteriskCount`, is optional. The default value is `1`. However, it is typed as mandatory in `index.d.ts`.

- https://github.com/Koromix/rygel/blob/433a0de7f7a5a7ada52d959bbfb528f559d5e92d/src/koffi/index.d.ts#L108

```ts
    export function pointer(name: string, ref: TypeSpec, asteriskCount: number): IKoffiCType;
```

It should be 

```ts
    export function pointer(name: string, ref: TypeSpec, asteriskCount?: number): IKoffiCType;
```

**Comment by Koromix** [comment]
Good catch, thanks :)
