### ISSUE TITLE
`koffi.call()` is missing in `index.d.ts`

### ISSUE THREAD

**Issue by tamuratak** [Koromix/koffi#119]
`koffi.call()` is documented at https://koffi.dev/functions#call-pointer-directly. However, it is missing in `index.d.ts`, https://github.com/Koromix/rygel/blob/master/src/koffi/index.d.ts.

```
koffi: v2.7.0
node: v18.19.0
```

**Comment by Koromix** [comment]
Thanks for the report, I've added this in the latest commit :)
