### ISSUE TITLE
how to pass the pointer of a structure having members are two different structure.

### ISSUE THREAD

**Issue by JaatDeveloper** [Koromix/koffi#120]
c++ code :

		struct struct1
		{
			uint32_t    m_uLevel;                       
			uint8_t     m_bool;                      
			wchar_t     m_sPath[64]; 
			wchar_t     m_sName[64];
		};

		struct struct2
		{
			uint8_t m_bool;                     
			wchar_t m_sPath[64]; 
			wchar_t m_sKeyPath[64]; 
			wchar_t m_sKey[64];    
		};

		struct MainStruct
		{
			struct1         m_struct1;
			struct2         m_struct2;
		};
		
		int MyFunc(const MainStruct* arg_struct);
		
Javascript Code : 	

	const myLib = koffi.load('myLib.dll');	
	
	//first try 
	const MyFuncKoffi = myLib.func('MyFunc', 'int', ['MainStruct *']);
	
	//second try 
	const MainStructPtr = koffi.pointer('MainStruct');
	const MyFuncKoffi = myLib.func('MyFunc', 'int', [MainStructPtr]);
	
	
	///main area

    let struct1_var = {
        m_uLevel: 0,
        m_bool: 1,
        m_sPath: Array.from(local_Path),
        m_sName: Array.from(local_Name)
    }
	
	let struct2_var = {
        m_bool: 0,
        m_sPath: Array.from(local_Path),
        m_sPath: Array.from(local_Path),
        m_sName: Array.from(local_Name)
    }

    let mainlist = [struct1_var, struct2_var];
    var Result = MyFuncKoffi(mainlist);

Function call is going to the dll side but the values do not seems appropriate.

**Comment by JaatDeveloper** [comment]
the problem i am facing while trying to upgrade the node.js and need touse koffi instead of ref-napi previous code snippet which one was working 👍 
	var mainlist = new MainStruct({
        struct1_var: 
		{ m_uLevel: 0,
        m_bool: 1,
        m_wsPath: Array.from(local_Path),
        m_wsName: Array.from(local_Name)
		},
        struct2_var: 
		{ m_bool: 0,
        m_sPath: Array.from(local_Path),
        m_wsPath: Array.from(local_Path),
        m_wsName: Array.from(local_Path) 
		}
   });
    
    var Result = MyFuncKoffi(mainlist.ref());

also have noticed that the structure do not support the structure's constructor on new.

**Comment by Koromix** [comment]
The `new` thing you use with node-ffi and the ref stuff is indeed not a thing in Koffi. Simple flat objects are used instead (aka duck typing).

In your example, you're giving an array of two objects to Koffi when calling MyFunc (`[struct1_var, struct2_var]`), which Koffi interprets as: *here are two objects that should look like MainStruct objects, please convert them to a `MainStruct[2]` array and give the address to the function*. Obviously not what you intended.

You must instead give it a proper MainStruct object, as I do in the following example:

```c
// Windows: clang -shared -o 120.dll 120.c
// Linux: clang -shared -o 120.so 120.c

#include <stdint.h>
#include <wchar.h>

#ifdef _WIN32
    #define EXPORT __declspec(dllexport)
#else
    #define EXPORT __attribute__((visibility("default")))
#endif

struct struct1 {
    uint32_t m_uLevel;
    uint8_t m_bool;
    wchar_t m_sPath[64]; 
    wchar_t m_sName[64];
};

struct struct2 {
    uint8_t m_bool;
    wchar_t m_sPath[64];
    wchar_t m_sKeyPath[64];
    wchar_t m_sKey[64];
};

struct MainStruct {
    struct struct1 m_struct1;
    struct struct2 m_struct2;
};

EXPORT int MyFunc(const struct MainStruct *arg_struct)
{
    wprintf(L"struct1.m_sPath = %ls\n", arg_struct->m_struct1.m_sPath);
    wprintf(L"struct2.m_sKey = %ls\n", arg_struct->m_struct2.m_sKey);

    return (int)arg_struct->m_struct1.m_uLevel;
}
```

```js
const koffi = require('koffi');
const myLib = koffi.load('./120' + koffi.extension);

// Declarations

const struct1 = koffi.struct('struct1', {
    m_uLevel: 'uint32_t',
    m_bool: 'uint8_t',
    m_sPath: koffi.array('char16', 64),
    m_sName: koffi.array('char16', 64)
});
const struct2 = koffi.struct('struct2', {
    m_bool: 'uint8_t',
    m_sPath: koffi.array('char16', 64),
    m_sKeyPath: koffi.array('char16', 64),
    m_sKey: koffi.array('char16', 64)
});
const MainStruct = koffi.struct('MainStruct', {
    m_struct1: struct1,
    m_struct2: struct2
});

const MyFuncKoffi = myLib.func('MyFunc', 'int', ['MainStruct *']);
// Alternatve: const MyFuncKoffi = myLib.func('MyFunc', 'int', [koffi.pointer(MainStruct)]);

// Main code

let local_Path = '/path/to/stuff';
let local_Name = 'name_of_stuff';

let mainlist = {
    m_struct1: {
        m_uLevel: 42,
        m_bool: 1,
        m_sPath: local_Path, // You can skip the Array.from it'll perform better,
                             // Koffi handles string to char[n] and char16[n] conversion
        m_sName: local_Name
    },

    m_struct2: {
        m_bool: 0,
        m_sPath: local_Path,
        m_sKeyPath: local_Path,
        m_sKey: local_Name
    }
}

var Result = MyFuncKoffi(mainlist);
console.log(Result);
```

**Comment by JaatDeveloper** [comment]
thanks this was exactly what i wanted. Resolved
