### ISSUE TITLE
Problems with _Out_ char**

### ISSUE THREAD

**Issue by mathiasbockwoldt** [Koromix/koffi#121]
I am currently transitioning from ffi-napi to koffi. Thank you very much for this library!

I have one particular function that troubles me. I do not have access to the source code of the C function, only the header. The signature is `int getNames(int, int, _Out_ char**)`. The basic idea is that the function should fill the `char**` with names from a database based on the two `int` parameters. So, after calling the function, the last parameter should look something like `['Adam', 'Beatrice']` (probably filled with null bytes).

On the JavaScript side, I tried several variations for the last parameter (a bit simplified to two elements here for brevity):

```js
const names1 = [ '\0'.repeat(10), '\0'.repeat(10) ];
const names2 = [ [ '\0'.repeat(10), '\0'.repeat(10) ] ];
const names3 = [ [ '\0'.repeat(10) ], [ '\0'.repeat(10) ] ];
```

All of them lead to a segfault. I am sure that the provided length of the null byte strings is sufficient, so it must be something else.
Any idea what I am doing wrong? I tried to find anything in the docs or tests, but to no avail.

**Comment by Koromix** [comment]
Could you give a bit more information?

Namely, the original API documentation, that details how you're supposed to use this function from C.

**Comment by mathiasbockwoldt** [comment]
Wow, thank you for the quick answer!

Unfortunately, this is all information I have. I can check with the people who wrote the code, but that'll take some time.

```c
/*!
* Returns names of elements in a database.
*
* @param[in] uniqueId ID of an existing database.
* @param[in] maxElementNameLen Maximum length of individual element names.
*
* @param[out] elementNames Element names, vector size number of elements in the table.
*
* @pre Caller is responsible for making sure elementNames is large enough to hold the number of elements in the database.
*
* @sa getNumberOfElements
*
* @return error code (0 on success)
*/
OUR_API int OUR_CALL getElementNames(int uniqueId,
    int maxElementNameLen,
    char** elementNames);
```

**Comment by mathiasbockwoldt** [comment]
OK, got a super-quick answer from the people who made the code. Some parts had to be redacted 🙄 , but this should be the gist of it.

```c
int getElementNames(int uniqueId, int maxElementNameLen, char** elementNames) {
  int nElem = someMagicSourceOfNumberOfElements(uniqueId);
  for (int i = 0; i < nElem; ++i) {
    std::string tmp = someMagicSourceOfStrings(uniqueId);
    int nameCopyLen = std::min(static_cast<int>(tmp.length()), maxElementNameLen - 1);
    for (int j = 0; j < nameCopyLen; ++j) {
      elementNames[i][j] = tmp[j];
    }
    elementNames[i][nameCopyLen] = '\0';
  }
  return 0; // original code is more sophisticated...
}
```

**Comment by Koromix** [comment]
Thanks! The reason I asked is because the answer depends on how the strings are allocated. Here, it is the responsability of the caller to preallocate both (1) an array of pointers and (2) buffer space for each string.

I've used your code to make a working C++ sample code:

```cxx
// Windows: clang++ -shared -o 121.dll 121.cc
// Linux: clang++ -shared -o 121.so 121.cc

#include <string>

#ifdef _WIN32
    #define EXPORT extern "C" __declspec(dllexport)
#else
    #define EXPORT extern "C" __attribute__((visibility("default")))
#endif

EXPORT int getElementNames(int uniqueId, int maxElementNameLen, char** elementNames);

static int someMagicSourceOfNumberOfElements(int uniqueId)
{
    switch (uniqueId) {
        case 0: return 1;
        case 1: return 6;
        default: return 0;
    }
}

static std::string someMagicSourceOfStrings(int uniqueId, int i)
{
    static const char *strings[] = {
        "foo",
        "bar",
        "FOOBAR",
        "barfoo",
        "hello",
        "world"
    };

    return strings[i];
}

EXPORT int getElementNames(int uniqueId, int maxElementNameLen, char** elementNames)
{
    int nElem = someMagicSourceOfNumberOfElements(uniqueId);
    for (int i = 0; i < nElem; ++i) {
        std::string tmp = someMagicSourceOfStrings(uniqueId, i);
        int nameCopyLen = std::min(static_cast<int>(tmp.length()), maxElementNameLen - 1);
        for (int j = 0; j < nameCopyLen; ++j) {
            elementNames[i][j] = tmp[j];
        }
        elementNames[i][nameCopyLen] = '\0';
    }
    return 0;
}
```

And here is how to use it from Node.js with Koffi:

```js
const koffi = require('koffi');
const lib = koffi.load(__dirname + '/121' + koffi.extension);

// Declarations

const getElementNames = lib.func('int getElementNames(int uniqueId, int maxElementNameLen, _Inout_ char **elementNames)');

// Wrapper

function callGetElementNames(uniqueId) {
    // Provide enough space for elements, as per documentation, this
    // will work for 64 elements at most
    let maxElements = 64;

    // Each name can be 255 (+ terminating NUL byte) characters at most
    let maxElementNameLen = 256;

    let dest = Array(maxElements).fill('\0'.repeat(maxElementNameLen));

    if (getElementNames(uniqueId, dest.length, dest) != 0)
        throw new Error('getElementNames() failed');

    // Truncate empty strings at the end
    let len = dest.indexOf('');
    dest.length = (len >= 0) ? len : dest.length;

    return dest;
}

// Test

let elements = callGetElementNames(1);
console.log(elements);
```

Because each individual string buffer is provided by the caller, you need to use `_Inout_` so that Koffi copies each buffer (sized `maxElementNameLen`). Which then gets filled by the C++ code, and converted back to strings by Koffi.

**Comment by mathiasbockwoldt** [comment]
Great, this works! Thank you very much for your quick and competent help!

Maybe the source code you wrote (or a simplified version of it) would make a nice addition to the documentation of koffi? The key I was missing was the `_Inout_` which doesn't have an example in the docs, yet.

**Comment by Koromix** [comment]
You're welcome :)

Yes, good idea, I'll add several examples for "function returns an array of strings" API. There are multiple C API styles to handle this, and each one works differently.

An example for each style would definitely help!
