### ISSUE TITLE
The dwSize attribute is missing

### ISSUE THREAD

**Issue by scvzerng** [Koromix/koffi#122]
I am migrating a java jna camera dynamic library,But defining to pass `dwSize` in koffi does not correctly pass whether the property needs to be passed in another way
[demo](https://github.com/scvzerng/koffi-dwsize.git)

**Comment by Koromix** [comment]
Use `koffi.inout()` instead of `koffi.out()` for your output parameters, if anything (such as `dwSize`) needs to be copied from JS to C. With `koffi.inout()`, it will be, and then the entire output struct will be converted back to a JS object.

So, in and out, both ways :)

**Comment by scvzerng** [comment]
Maybe I didn't go into enough detail, but I'm referring to the first input parameter,Now that I've used koffi.inout, I still can't pass dwSize correctly
```
 CLIENT_LoginWithHighLevelSecurity: lib.func("CLIENT_LoginWithHighLevelSecurity", long, [
        koffi.inout(koffi.pointer(NET_IN_LOGIN_WITH_HIGHLEVEL_SECURITY)),
        koffi.out(koffi.pointer(NET_OUT_LOGIN_WITH_HIGHLEVEL_SECURITY)),
    ]),
```
This is the dll documentation description
![1704848889965](https://github.com/Koromix/koffi/assets/14892120/b8ee662f-d5b8-4bec-96dc-317ee1c31eb7)
![1704848943575](https://github.com/Koromix/koffi/assets/14892120/5f1b25d2-03e3-44ef-b98e-61e73c6fe16f)

**Comment by scvzerng** [comment]
> Use instead of for your output parameters, if anything (such as ) needs to be copied from JS to C.`koffi.inout()``koffi.out()``dwSize`
> 
> With , it will be, and then the entire output struct will be converted back to a JS object.`koffi.inout()`
> 
> So, in and out, both ways :)

Maybe I didn't go into enough detail, but I'm referring to the first input parameter,Now that I've used koffi.inout, I still can't pass dwSize correctly
```
 CLIENT_LoginWithHighLevelSecurity: lib.func("CLIENT_LoginWithHighLevelSecurity", long, [
        koffi.inout(koffi.pointer(NET_IN_LOGIN_WITH_HIGHLEVEL_SECURITY)),
        koffi.out(koffi.pointer(NET_OUT_LOGIN_WITH_HIGHLEVEL_SECURITY)),
    ]),
```
This is the dll documentation description
![1704848889965](https://github.com/Koromix/koffi/assets/14892120/b8ee662f-d5b8-4bec-96dc-317ee1c31eb7)
![1704848943575](https://github.com/Koromix/koffi/assets/14892120/5f1b25d2-03e3-44ef-b98e-61e73c6fe16f)

**Comment by scvzerng** [comment]
I'm sorry for a low-level error. I didn't realize that dwSize was set on the java side, and I thought that the output parameter would set dwSize by itself. Maybe I still lack knowledge of c, thank you for your answer
