### ISSUE TITLE
could i ask a question

### ISSUE THREAD

**Issue by 18259669383** [Koromix/koffi#123]
![图片](https://github.com/Koromix/koffi/assets/93261537/a0c5c930-e5e2-43ea-b7b5-2d653846460f)
This is C# code
![图片](https://github.com/Koromix/koffi/assets/93261537/8f32379f-6143-4571-81d5-ca239aa0908a)

This is electron code
my problem
  Use js to mimic c# to implement this logic , The problem is that the sb variable in c#, don't know how the syntax is written , Hopefully it will be answered

**Comment by scvzerng** [comment]
try new Int8Array(1024)

**Comment by 18259669383** [comment]
> const out = new Int8Array(1024);

![图片](https://github.com/Koromix/koffi/assets/93261537/c6e02788-7d1d-4ef5-b14e-055e5b7851ef)
be not allowed

**Comment by scvzerng** [comment]
Try replacing char with  uint8_t

**Comment by 18259669383** [comment]
thank you，Could you buy me a cup of coffee，I am from China，whether there is weixin

**Comment by scvzerng** [comment]
我也是中国的，以后有兴趣可以一起交流
