### ISSUE TITLE
char*** as out parameter

### ISSUE THREAD

**Issue by cedric-mynotary** [Koromix/koffi#129]
Hello, 

Not sure if it's a misuse or a real issue...
I use koffi to wrap a C library, it works like a charm (and THANKS for that !) except for one function with this signature:

`int myFunction(int someParam, char *** out);`

The lib's doc says that out is an _"address of a pointer to an array of char array. Caller should initialize the pointer value
to NULL. After a successful call, the pointer will be filled with the address of an array containing
the list of [blah blah]"_

I tried this definition : `lib.func('int myFunction(int, _Out_ char*** out)');  // tried str** too`
Upon call I tried these initial values for out : `[], [[]], [['']]`, the value after the call is {} (not even an array!)
The initial value `[null]` gives me in return ['0']

I'm sure of what is actually returned by the function, as I happen to have a reference implementation (a java wrapper). I should get an array of 3 strings.

Any idea on how to retrieve the return values correctly ?

**Comment by Koromix** [comment]
I've published Koffi 2.7.3 to make it slightly easier to decode NULL terminated arrays, which my example below uses. Install latest Koffi version to test my code below.

Tested on Linux and uses the non-standard function asprintf() for simplicity.

```c
// clang -shared -Wall -o 129.so 129.c

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>

void release_strings(char **ptr);

// Creates a NULL terminated array of strings, each string is itself NUL temrinated
int create_strings(int value, char ***out)
{
    int count = value % 8;

    char **ptr = calloc(count + 1, sizeof(char *));
    if (!ptr)
        goto error;

    for (int i = 0; i < count; i++) {
        if (asprintf(&ptr[i], "%d: %d", i, i * value) < 0)
            goto error;
    }

    *out = ptr;
    return 0;

error:
    release_strings(ptr);
    return -1;
}

// Release strings and the array itself
void release_strings(char **ptr)
{
    if (!ptr)
        return;

    for (int i = 0; ptr[i]; i++) {
        free(ptr[i]);
    }

    free(ptr);
}
```

```js
const koffi = require('koffi');

const lib = koffi.load('./129.so');
const create_strings = lib.func('int create_strings(int n, _Out_ char ***out)');
const release_strings = lib.func('void release_strings(char **ptr)');

let out = [null];
if (create_strings(19, out) < 0)
    throw new Error('create() failed');
let ptr = out[0];

// Both koffi.decode() and koffi.encode() are not very intuitive and will be replaced by better alternatives soon
// Until then... this will do.
let strings = koffi.decode(ptr, 'void *', -1).map(ptr => koffi.decode(ptr, 'char', -1));
console.log(strings);

release_strings(ptr);
```

**Comment by cedric-mynotary** [comment]
And it works, thank you @Koromix !
decode/encode seem really powerful, maybe they just need more detailed explanation on how they work ? I didn't see them in the docs before either, I'm not concerned with exported variables so I skipped that part... 

Anyway, you saved my day !

**Comment by Koromix** [comment]
Yes, I want to document them more/better.

But their API is confusing so I want to make a slightly better API before I do, and deprecate encode/decode once a less confusing API exists.
