### ISSUE TITLE
Open the window in the dll function, and the window will always be stuck.

### ISSUE THREAD

**Issue by tuyangJs** [Koromix/koffi#132]
![image](https://github.com/Koromix/koffi/assets/38270397/3378f36d-668a-416f-b479-9c2bfd5246af)
Both synchronous and asynchronous can cause windows to freeze
```
 ipcDLLbacks.async(data.channel, errs, DLLtemp, nullFunc)
           // ipcDLLbacks(data.channel, errs, DLLtemp)
```

**Comment by Koromix** [comment]
There is not enough information for me to speculate or test anything. I need a small reproducible example.
