### ISSUE TITLE
How to define (or export) koffi aliases and pointers when they are shared by multiple files? 

### ISSUE THREAD

**Issue by melihcoban** [Koromix/koffi#137]
I am using koffi with Electron where I implemented few shared libraries therefore they share some aliases and pointers.

class1.ts
```ts
import koffi from 'koffi';

const WORD = koffi.alias('WORD', 'uint16_t');
// more shared types and types specific to this .dll

class Class1 {
// class implementation

initialize() {...}
}
```

class2.ts
```ts
import koffi from 'koffi';

const WORD = koffi.alias('WORD', 'uint16_t');
// more shared types and types specific to this .dll

class Class2 {
// class implementation
}

initialize() {...}
```

In main (index.ts) file of the electron I create instances of these classes. However, when I create an instance of a class which shares some aliases and pointers with different class I am getting an error. In this example it is ```Type name 'WORD' already exists```.

I tried defining aliases and pointers in the index.ts of the electron, however this time other files cannot find the types. ``` Reference Error: WORD is not defined```

I fixed the issue by creating another file named ```initialize-koffi``` where I define the aliases and call an empty method ```ts initializeKoffiTypes()``` in the index.ts for definitions. 

```ts
import koffi from 'koffi';

const WORD = koffi.alias('WORD', 'uint16_t');
const DWORD = koffi.alias('DWORD', 'uint32_t');
const VOID = koffi.alias('VOID', 'void');
const BYTE = koffi.alias('BYTE', 'unsigned char');
const WCHAR = koffi.alias('WCHAR', 'char16_t');
const SCARDCONTEXT = koffi.alias('SCARDCONTEXT', 'long *');
const SCARDHANDLE = koffi.alias('SCARDHANDLE', 'long *');

// Pointers

/* @ts-ignore */
const HANDLE = koffi.pointer('HANDLE', koffi.opaque());
/* @ts-ignore */
const LPVOID = koffi.pointer('LPVOID', VOID);
/* @ts-ignore */
const LPHANDLE = koffi.pointer('LPHANDLE', HANDLE);
/* @ts-ignore */
const LPDWORD = koffi.pointer('LPDWORD', DWORD);
/* @ts-ignore */
const LPTSTR = koffi.pointer('LPTSTR', WCHAR);
/* @ts-ignore */
const LPBYTE = koffi.pointer('LPBYTE', BYTE);
/* @ts-ignore */
const LPSCARDHANDLE = koffi.pointer('LPSCARDHANDLE', SCARDCONTEXT);
/* @ts-ignore */
const LPSCARDCONTEXT = koffi.pointer('LPSCARDCONTEXT', SCARDHANDLE);
/* @ts-ignore */
const LPCVOID = koffi.pointer('LPCVOID', VOID);
/* @ts-ignore */
const LPCBYTE = koffi.pointer('LPCBYTE', 'const unsigned char*');
/* @ts-ignore */
const LPCWSTR = koffi.pointer('LPCWSTR', WCHAR);
/* @ts-ignore */
const LPWSTR = koffi.pointer('LPWSTR', WCHAR);

export function initializeKoffiTypes() {
  console.log('Success!');
}
```

However, I do not believe this is a good solution. If this problem is not about koffi itself, we can just close the issue.

**Comment by Koromix** [comment]
Make a "koffi.js" file, export everything from there and import it in other files. When a module is imported multiple times, it is evaluated only once.
