### ISSUE TITLE
Define input and output parameters error

### ISSUE THREAD

**Issue by Liupeng8** [Koromix/koffi#139]
This is my first time using this plugin，I have never used it and do not understand C language. Please tell me how to define methods using koffi for a dynamic library with such a structure.
![image](https://github.com/Koromix/koffi/assets/23046680/ea79ec4d-8f90-43d9-b46d-10d59566f365)

my code
```
        this.lib = koffi.load(this.getDllPath('fsiapidll', 'NationECCode.dll'));
        const NationEcTrans = this.lib.func('char* __stdcall NationEcTrans(char *strUrl, char *InData, _Out_ char *OutData)');
        console.log(NationEcTrans)
        const inData = {
            orgId: '35020311234',
            businessType:"01101",
            operatorId:"test001",
            operatorName:"管理员",
            officeId:"45678",
            officeName:"消化内科",
            deviceType:"SelfService",
        }
        const strUrl = 'http://10.77.211.236/1.0.0/localQrCodeQuery';
        const uriArr = koffi.array('char', strUrl.length, 'String');
        const inDataArr = koffi.array('char', JSON.stringify(inData).length, 'String');
        const buf = Buffer.allocUnsafe(2048);
        NationEcTrans(uriArr, inDataArr, buf)
```

error message
![image](https://github.com/Koromix/koffi/assets/23046680/34d55776-c3a4-4793-881a-9ccd1bb8bd36)

**Comment by Koromix** [comment]
Please provide more information / a repro case. Interop with C typically requires knowing a little bit about C programming, even if Koffi tries to handle things automatically when possible.
