### ISSUE TITLE
Question on memory allocation per call

### ISSUE THREAD

**Issue by sfrieske** [Koromix/koffi#140]
When calling a lib function with a `koffi.struct` as argument, memory is probably allocated for each individual call (and freed appropriately), I assume. Is this assumption correct?

If this is correct, would using `koffi.alloc` once prevent koffi from allocating memory per call?

Background: My code calls a function ( [I2C ioctl](https://github.com/Koromix/koffi/issues/104#event-11086012290) ) permanantly, about 30 times per second. On a weak processor like Raspi Zero the o/s might become overwhelmed with garbage collection and eventually blocks for a few seconds.  Trying to avoid this as much as possible.

**Comment by Koromix** [comment]
Koffi reuses the same block of preallocated memory for each call, so you're good ;) By default, this block is 2 MiB.

It will make a temporary allocation only if the struct is bigger than 4 kiB, of if the preallocated  koblock is full.

More info here: https://koffi.dev/misc#memory-usage
