### ISSUE TITLE
Calling dll function with nodejs fails

### ISSUE THREAD

**Issue by A3PvdM** [Koromix/koffi#143]
I've some problems with calling functions in a special dll of software used in our company.

I made a vb.net file and compiled it to a dll.

> `
> Public Class TestDLL
>     Public Shared Function Add(ByVal a As Integer, ByVal b As Integer) As Integer
>         Return a + b
>     End Function
> End Class
> `

In nodeJS i wrote the code:

> `
> const testlib = koffi.load('BRCdll/testdll/testdll.dll');
> const Add = testlib.func('int __stdcall Add(int, int)');
> const result = Add(1, 2);
> console.log('result:', result);`

Output:

> const Add = testlib.func('int __stdcall Add(int, int)');
>                     ^
> Error: Cannot find function 'Add' in shared library

Why does this go wrong?

**Comment by Koromix** [comment]
AFAIK, C# and VB.net public methods don't use a pure C ABI. Please look into unmanaged exports.
