### ISSUE TITLE
Can't find function 'Say' in the shared liabrary

### ISSUE THREAD

**Issue by Riven94** [Koromix/koffi#145]
I'd like to use koffi to load a dll made by C#,but when I call the function, got the error
C# code example
`
name space SayHello
{
    public class MyClass
    {
        public string Say(string myName){
            return 'Hello' + myName;
        }
    }
}
`
and js code example
`
const koffi = require('koffi');
const path = require('path')
const myDll = path.resolve(__dirname, './SayHello.dll');
const say = lib.function('str Say(str)');
console.log(say('World'));
`

**Comment by Koromix** [comment]
AFAIK, C# public methods don't use a pure C ABI. Please look into unmanaged exports.
