### ISSUE TITLE
Structure parameter, cannot get an assignment

### ISSUE THREAD

**Issue by Linyefeilyft** [Koromix/koffi#146]
I have a c++ DLL that has a method as follows:
`long __stdcall Get_TermbData(char *szFileNameIn, TERMB_ITEM* pstOut)`
TERMB_ITEM structure is defined as follows:
`struct TERMB_ITEM
	{
		char pzTxt[70][128];
	};`

How do I get pstOut:
`const Get_TermbData = IDR_A2.func('long __stdcall Get_TermbData(char *szFileNameIn, TERMB_ITEM* pstOut)');
const pstOut = { };
device_result = Get_TermbData(path.join(process.resourcesPath, 'plugins/aaa.bmp'), pstOut);`
post-execution the pstOut is empty

**Comment by Koromix** [comment]
Annotate the parameter as "output", as documented here: https://koffi.dev/output

```js
const Get_TermbData = IDR_A2.func('long __stdcall Get_TermbData(char *szFileNameIn, _Out_ TERMB_ITEM* pstOut)');

const pstOut = { };
device_result = Get_TermbData(path.join(process.resourcesPath, 'plugins/aaa.bmp'), pstOut);
```

**Comment by Linyefeilyft** [comment]
Thanks, I got the "psout" value，but  "pzTxt" are there any chinese characters in this content ,cannot be displayed properly

**Comment by Linyefeilyft** [comment]
`struct TERMB_ITEM { char pzTxt[70][128] };`
pzTxt.length is 128?why?
