### ISSUE TITLE
Pointer arithmetic, or how to read length of BSTR correctly

### ISSUE THREAD

**Issue by lwahonen** [Koromix/koffi#148]
On Win32 many functions return a BSTR ( https://learn.microsoft.com/en-us/previous-versions/windows/desktop/automat/bstr )

The pointer returned is to the second member of the struct(!). You need to read the length of the string from ((int32_t*)bstr_pointer)[-1]. Is there a way to do pointer math with Koffi?

As documented, the strings may contain multiple null bytes so simply reading the character array until null can leave you with truncated data

**Comment by Koromix** [comment]
Here is an example to play with BSTR:

```js
const koffi = require('koffi');

const OLECHAR = koffi.alias('OLECHAR', 'char');
const BSTR = koffi.pointer('BSTR', koffi.opaque());

const oleaut32 = koffi.load('oleaut32.dll');
const SysAllocString = oleaut32.func('BSTR SysAllocString(const OLECHAR *str)');
const SysFreeString = oleaut32.func('void SysFreeString(BSTR str)');

function bstr_len(bstr) {
    let len = koffi.decode(bstr, -4, 'uint32_t');
    return len;
}

function bstr_str(bstr) {
    let len = bstr_len(bstr);
    let str = koffi.decode(bstr, 'char', len);
    return str;
}

let test = SysAllocString('Hello World!');

console.log(bstr_len(test));
console.log(bstr_str(test));

SysFreeString(test);
```
