### ISSUE TITLE
Add option to load shared libraries with the RTLD_GLOBAL flag

### ISSUE THREAD

**Issue by marianheinsen** [Koromix/koffi#149]
I use koffi to load a shared library from an external developer which requires itself to be loaded with the RTLD_GLOBAL flag. It would be great if I could set an option like _global: true_ in the object passed to the _koffi.load_ function, similiar to the existing _lazy_ property. This currently prevents me from using koffi, because the external library doesn't work correctly without the RTLD_GLOBAL flag @Koromix.

**Comment by Koromix** [comment]
I've added this and released Koffi 2.8.2 ;)
Documentation: https://koffi.dev/functions#loading-options

**Comment by marianheinsen** [comment]
Amazing! Thank you for the fast response.

**Comment by Life4gal** [comment]
> I've added this and released Koffi 2.8.2 ;) Documentation: https://koffi.dev/functions#loading-options

I'm using typescript, and it looks like `load` doesn't have that `option`.
https://github.com/Koromix/rygel/blob/a97a3194f9b0c684a3fab7671702ba48ed649aa6/src/koffi/index.d.ts#L23
