### ISSUE TITLE
v2.8.3 prebuild binaries are missing

### ISSUE THREAD

**Issue by ufukbakan** [Koromix/koffi#150]
Can't install koffi on my windows machine where CMake also is not installed.
Can you release prebuild binaries asap, and isnt it automated idk how it works

**Comment by Koromix** [comment]
It is automated, by me, with QEMU virtual machines for OS/arch with first-class support. For tests (there is a lot of OS and ABI-specific code in Koffi!) and builds.

But it's slow and memory-intense. My main machine was destroyed recently and it's kind of painful to run these VMs on the machine I'm using right now. So I have to do it a bit more manually than usual, and made a mistake (forgot the macos and windows prebuilds in 2.8.3).

FOSS does not pay much :) But you can tip me to help me buy a new machine if you want ;)
https://github.com/sponsors/Koromix?frequency=one-time&sponsor=Koromix

I've released Koffi 2.8.4 to fix this, it has all prebuilt binaries.
