### ISSUE TITLE
Structure name ending with a space

### ISSUE THREAD

**Issue by ecochard** [Koromix/koffi#151]
I know this is an error but we can declare a structure with space without error.

```js
const Rect = koffi.struct( "Rect ", {
	x: 'int',
	y: 'int',
	w: 'int',
	h: 'int',
} );
```

of course, i cannot use it later but the message is not clear:

```
Uncaught Error Error: Unknown or invalid type name 'Rect'
```

**Comment by Koromix** [comment]
Thanks for the report, next release will check for obvious errors (such as white spaces, or empty name "").
Won't be too strict though.

**Comment by Koromix** [comment]
It's in Koffi 2.8.5
