### ISSUE TITLE
2.6.3 Upgrade to 2.6.12 Fails Description

### ISSUE THREAD

**Issue by zhongyao-x** [Koromix/koffi#153]
`
 const GetValue = lib.func(487, 'bool', ['int', 'int', 'int', '_Out_ SENSOR_READ_RESULT *'])
`

Calling GetValue does not return the data correctly. 2.6.3 is OK

**Comment by Koromix** [comment]
Hi, there's not enough info for me to do anything.

Please provide more code and information about the API you are trying to call. Ideally, provide a minimal repro code that works with 2.6.3 and fails with 2.6.12.

**Comment by Koromix** [comment]
Please reopen if you have more information.
