### ISSUE TITLE
Inout buffer containing array of structures

### ISSUE THREAD

**Issue by Nevyn75** [Koromix/koffi#156]
Hi.

I have a function:

`int ClientGetEventsList(unsigned char** eventsBuffer, int* eventsNumber);`

The buffer eventsBuffer is allocated internally.
If success it should return an array of structures in the pointer.

The base structure should be the following:

```
const Event = koffi.pack('Event', {
	time: koffi.array('char', 32, 'String'),
	action: 'int'
});
```

I call the function this way:

```
let eventsNumber = [0];
let eventsBuffer = [{}]

const ClientGetEventsList = lib.func('int ClientGetEventsList(_Inout_ char** eventsBuffer, _Out_ int* eventsNumber)');
ret = ClientGetEventsList(eventsBuffer, eventsNumber);
```
Everything seems OK and eventsNumber results > 1.
How can I cast the result to see all structures inside the array?

Can I free the buffer from Node? Should I import the "free" function?

Thank you very much for any help you could give me.

**Comment by Koromix** [comment]
HOpefully I got it right, I'd try this:

```js
let events = koffi.decode(eventsBuffer[0], Event, eventsNumber[0]);
console.log(events);

koffi.free(eventsBuffer[0]);
```
