### ISSUE TITLE
Seeking Advice on Migrating from FFI to Koffi

### ISSUE THREAD

**Issue by lustrc** [Koromix/koffi#157]
```import iconv from 'iconv-lite';
import ref from 'ref-napi';
const Struct = require('ref-struct-di')(ref);
const ArrayType = require('ref-array-di')(ref);
import koffi from 'koffi';

const MsgBuffer = Struct({
  type: 'int',
  user_name: ArrayType('byte', 0x20),
  group_name: ArrayType('byte', 0x80),
  text: ArrayType('byte', 0x3a0),
});

const MsgBufferRef = ref.refType(MsgBuffer );

const MsgData = Struct({
  _1: 'uint64',
  size: 'uint64',
  data: MsgBufferRef ,
  name: 'string',
  _2: ArrayType('byte', 0x10),
  _3: ArrayType('byte', 0x10),
});

export function send_msg(
  userName,
  groupName,
  text: string,
  type: number
): number {
  const msg_buffer = new MsgBuffer();
  msg_buffer.type = type;

  const user_name = iconv.encode(userName, 'gbk');
  const group_name = iconv.encode(groupName, 'gbk');
  const text_ucs2 = iconv.encode(text, 'gbk');

  Buffer.from(user_name).copy(data.user_name.buffer);
  Buffer.from(group_name).copy(data.group_name.buffer);
  Buffer.from(text_ucs2).copy(data.text.buffer);

  const msg_data = new MsgData ();
  msg_data.size= 0x484;
  msg_data.data= data.ref();

  const user_lib = koffi.load('user32.dll');

  const FindWindowA = user_lib.func('__stdcall', 'FindWindowA', 'int', [
    'str',
    'str',
  ]);

  const SendMessageA = user_lib.func('__stdcall', 'SendMessageA', 'int', [
    'int',
    'int',
    'int',
    'void *',
  ]);

  const hwnd = FindWindowA(null, 'alics');
  if (hwnd == 0) return -1;
  return SendMessageA(hwnd, 0x999, 0, msg_data.ref());
}
```

Any advice or examples would be greatly appreciated. Here's what I've implemented so far:

```
const MsgBuffer = koffi.pack('msg_buffer', {
  type: 'int',
  user_name: koffi.array('int8', 0x20),
  group_name: koffi.array('int8', 0x80),
  text: koffi.array('int8', 0x3a0),
});

export const MsgData = koffi.pack('msg_data', {
  _1: 'uint64',
  size: 'uint64',
  data: koffi.pointer(MsgBuffer),
  name: 'str',
  _2: koffi.array('int8', 0x10),
  _3: koffi.array('int8', 0x10),
});`
```

**Comment by Koromix** [comment]
Untested:

```js
import koffi from 'koffi';

const MsgBuffer = koffi.struct('MsgBuffer', {
    type: 'int',
    user_name: koffi.array('uint8', 0x20),
    group_name: koffi.array('uint8', 0x80),
    text: koffi.array('uint8', 0x3a0)
});

const MsgData = koffi.struct('MsgData', {
    _1: 'uint64',
    size: 'uint64',
    data: koffi.pointer(MsgBuffer),
    name: 'string',
    _2: koffi.array('uint8', 0x10),
    _3: koffi.array('uint8', 0x10)
});

const user32 = koffi.load('user32.dll');

// Please find and define functions only once for performance
const FindWindowA = user32.func('__stdcall', 'FindWindowA', 'int', [
    'str',
    'str',
]);
const SendMessageA = user32.func('__stdcall', 'SendMessageA', 'int', [
    'int',
    'int',
    'int',
    'void *',
]);

export function send_msg(userName, groupName, text, type) {
    const msg_buffer = {
        type: type,
        user_name: iconv.encode(userName, 'gbk'),
        group_name: iconv.encode(groupName, 'gbk'),
        text: iconv.encode(text, 'gbk')
    };

    const msg_data = {
        size: koffi.sizeof(MsgBuffer),
        data: msg_buffer,
        name: '' // XXX: Provide something here? or null?
    };

    const hwnd = FindWindowA(null, 'alics');
    if (hwnd == 0)
        return -1;
    return SendMessageA(hwnd, 0x999, 0, koffi.as(msg_data, 'MsgData *'));
}
```

**Comment by lustrc** [comment]
> 未经测试：
> 
> ```js
> import koffi from 'koffi';
> 
> const MsgBuffer = koffi.struct('MsgBuffer', {
>     type: 'int',
>     user_name: koffi.array('uint8', 0x20),
>     group_name: koffi.array('uint8', 0x80),
>     text: koffi.array('uint8', 0x3a0)
> });
> 
> const MsgData = koffi.struct('MsgData', {
>     _1: 'uint64',
>     size: 'uint64',
>     data: koffi.pointer(MsgBuffer),
>     name: 'string',
>     _2: koffi.array('uint8', 0x10),
>     _3: koffi.array('uint8', 0x10)
> });
> 
> const user32 = koffi.load('user32.dll');
> 
> // Please find and define functions only once for performance
> const FindWindowA = user32.func('__stdcall', 'FindWindowA', 'int', [
>     'str',
>     'str',
> ]);
> const SendMessageA = user32.func('__stdcall', 'SendMessageA', 'int', [
>     'int',
>     'int',
>     'int',
>     'void *',
> ]);
> 
> export function send_msg(userName, groupName, text, type) {
>     const msg_buffer = {
>         type: type,
>         user_name: iconv.encode(userName, 'gbk'),
>         group_name: iconv.encode(groupName, 'gbk'),
>         text: iconv.encode(text, 'gbk')
>     };
> 
>     const msg_data = {
>         size: koffi.sizeof(MsgBuffer),
>         data: msg_buffer,
>         name: '' // XXX: Provide something here? or null?
>     };
> 
>     const hwnd = FindWindowA(null, 'alics');
>     if (hwnd == 0)
>         return -1;
>     return SendMessageA(hwnd, 0x999, 0, koffi.as(msg_data, 'MsgData *'));
> }
> ```

Thank you for your response. After running the code, the line user_name: iconv.encode(userName, 'gbk') results in an error: 'Error: Expected array or buffer of size 32, got 8.

**Comment by Koromix** [comment]
Indeed, Koffi checks that buffer size matches the declared type. Which I don't like, actually.

So I'll publish Koffi 2.8.8 shortly which will change that, and the copy won't be necessary and my example should work as-is.

**Comment by Koromix** [comment]
Koffi 2.8.8 is published
