### ISSUE TITLE
How to define enum type to C

### ISSUE THREAD

**Issue by MenbinX** [Koromix/koffi#163]
The enum type in C is just like this:
```c
typedef enum
{
    SUCCESS   = 0, 
    PARAMETER = 1, 
    OPEN = 2,      
} RET_CODE;
```
And my C function is
```c
RET_CODE close_device()
```

How to define enum type in koffi?

**Comment by Koromix** [comment]
I'll probably add koffi.enum() to Koffi 3.0 to help a bit, but it won't do much more than combine three steps:

- Detect the appropriate integer type
- Make an alias
- Return a map of enum values

**Comment by MenbinX** [comment]
> C enums are stored as integers. In a simple `int`, unless something bigger is needed (such as `unsigned int`, `int64_t`, `uint64_t`).
> 
> In your case I'd simply use an alias and store the values on the side.
> 
> ```js
> const RET_CODE_TYPE = koffi.alias('RET_CODE', 'int');
> 
> const RET_CODE = {
>     SUCCESS: 0,
>     PARAMETER: 1, 
>     OPEN: 2    
> };
> 
> const close_device = lib.func('RET_CODE close_device()');
> 
> let ret = close_device();
> 
> if (ret == RET_CODE.SUCCESS) {
>     // SUCCESS
> } else if (ret == RET_CODE.PARAMETER) {
>     // PARAMETER
> } else if (ret == RET_CODE.OPEN) {
>     // OPEN
> } else {
>     // WTF
> }
> ```

Thanks. It helps me
