### ISSUE TITLE
Novice Question。How to call this windows api: AccSetRunningUtilityState

### ISSUE THREAD

**Issue by jiandanfs** [Koromix/koffi#165]
The electron v30 I am using
be deeply grateful!!!!!

**Comment by neko-para** [comment]
This api is quite ordinary, what you need is to simply open oleacc.dll and call it. You can simple treat HWND as a pointer, and use other api (e.g. GetForegroundWindow)to obtain it.

```c++
HRESULT AccSetRunningUtilityState(
  [in] HWND  hwndApp,
  [in] DWORD dwUtilityStateMask,
  [in] DWORD dwUtilityState
);
```
