### ISSUE TITLE
Latest 2.8.10 build breaks in Docker container running Alpine3.19 - loader (ld) issue

### ISSUE THREAD

**Issue by ggryschuk** [Koromix/koffi#168]
Hi. First just want to thank you again for your awesome software. Everything is working fine. At least it was until my latest rebuild of my Docker containers. Specifically I use the official node:22-alpine3.19 docker image as the base docker image for a base image of my own that is using koffi to load a bunch of C-Functions.

Long story short it all worked fine with the 2.8.9 build but when I went and rebuilt my base image it seems to have picked up the minor 2.8.10 release and I ran in to an issue when trying to load koffi (e..g at the simple const koffi = require('koffi') stage). Specifically I get an error of

Error loading shared library ld-linux-x86-64.so.2

Other then never receiving this error before it's not 'too' surprising in that I don't think Alpine uses this ld loader, at least in my docker containers there is no such loader though I do have 'ld-musl-x86_64.so.1'.

If I pin my docker build to using the 2.8.9 version of koffi (in the package.json that installs it) I get a working docker build again.

If it helps my docker build performs a 'koffi install' that basically runs

koffi node src/cnoke/cnoke.js -p . -d src/koffi --prebuild

thanks.

**Comment by Koromix** [comment]
Indeed, my fault :)
I'll release Koffi 2.8.11 with the fix in a few hours.

**Comment by ggryschuk** [comment]
Sounds good.

**Comment by Koromix** [comment]
It's out ;)

**Comment by ggryschuk** [comment]
It seems to be working.

thanks.
