### ISSUE TITLE
Can I use other encoding modes for conversion C to js 

### ISSUE THREAD

**Issue by MileahFa** [Koromix/koffi#169]
I am sorry that I do not speak English well.

In Doc  
~
Fixed-size string buffers
Koffi can also convert JS strings to fixed-sized arrays in the following cases:

char arrays are filled with the **UTF-8** encoded string, truncated if needed. The buffer is always NUL-terminated.
~

Can I use other encoding modes for conversion   .   for example   GBK

**Comment by Koromix** [comment]
Yes, but it's outside the scope of Koffi.

Follow my example here: https://github.com/Koromix/koffi/issues/15#issuecomment-1641725742

**Comment by MileahFa** [comment]
Thanks for the response.
