### ISSUE TITLE
Change of "process.env.LD_LIBRARY_PATH" in  Linux without effect on "koffi.load()"

### ISSUE THREAD

**Issue by MatthiasGuelck** [Koromix/koffi#170]
I use a C++ library (myLib) under Typescript, which is dependent on other libraries (including "myDependencyLib").
All libraries are located together in one directory.

In Windows I have extended the library search path with "kernel32.SetDllDirectoryA(path.resolve(__dirname, '(/myProject /pathToMyLibs'))".
As a result, all libraries are found under Windows when "koffi.load(path.resolve(__dirname, '(/myProject /pathToMyLibs/myLib.dll'))" is called.

For Linux I have adapted the environment variable "process.env.LD_LIBRARY_PATH=/myProject /pathToMyLibs".
From my typescript I display all library dependencies with "ldd(path.resolve(__dirname, '(/myProject /pathToMyLibs/myLib.so'))".
All necessary libraries are found.
When calling "koffi.load(path.resolve(__dirname, '(/myProject /pathToMyLibs/myLib.so'))" the library "myLib.so" is found.
However, the following error message is then displayed:
"**Error: Failed to load shared library: myDependencyLib.so: cannot open shared object file: No such file or directory
        at Object.<anonymous>.module.exports.load (/myProject/node_modules/koffi/index.js:542:13**"
In the output of "ldd", "myDependencyLib.so" is the first library on which "myLib.so" depends.

Apparently the change of "process.env.LD_LIBRARY_PATH" does not affect the behavior of "koffi.load()".

**Comment by Koromix** [comment]
LD_LIBRARY_PATH is read when the program starts, and is managed by the C runtime/init code (crt0). 

Its value is cached and so changing it later does not work for the current process. However, it will propagate to spawned processes (ldd in your example) where it will work.

Two solutions:

- Re-exec your own process if you detect that LD_LIBRARY_PATH is not what you want
- Execute through a wrapper shell script that sets LD_LIBRARY_PATH before executing your code

I'd suggest the first solution, with something like this:

```js
const koffi = require('koffi');

const needed_path = '/usr/local/lib';

if (process.env.LD_LIBRARY_PATH != needed_path) {
    const libc = koffi.load('libc.so.6');

    const execv = libc.func('int execv(const char *path, char **argv)');
    const fcntl = libc.func('int fcntl(int fd, int op, ...)');
    const F_SETFD = 2;
    const FD_CLOEXEC = 1;
    const setenv = libc.func('int setenv(const char *name, const char *value, int overwrite)');
    const strerror = libc.func('char *strerror(int errnum)');

    // It appears that Node sets FD_CLOEXEC on stdin/stdout/stderr, fix this
    fcntl(0, F_SETFD, 'int', 0);
    fcntl(1, F_SETFD, 'int', 0);
    fcntl(2, F_SETFD, 'int', 0);

    setenv('LD_LIBRARY_PATH', needed_path, 1);

    // Replaces the current process, so nothing should execute after!
    let argv = [...process.argv, null];
    execv(process.execPath, argv);

    console.error('Failed to exec to set LD_LIBRARY_PATH:', strerror(koffi.errno()));
    process.exit(1);
}

console.log('We made it:', process.env.LD_LIBRARY_PATH);
```

**Comment by MatthiasGuelck** [comment]
Thank you so much for the information and the sample code!
I will probably need a week before I can start implementing your suggestions.
After that I will let you know if it works.

**Comment by MatthiasGuelck** [comment]
I have already tried your suggestion.
It seems that the change works so far that LD_LIBRARY_PATH set to "/myProject /pathToMyLibs" is now taken into account.
Unfortunately, LD_LIBRARY_PATH is not additionally searched for shared object files, but only. 
Therefore I get the following error messages after replacing the process with "execv(process.execPath, argv);":
/usr/bin/node: /myProject/pathToMyLibs/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /usr/bin/node)
/usr/bin/node: /myProject/pathToMyLibs/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/bin/node)
/usr/bin/node: /myProject/pathToMyLibs/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/node)

**Comment by MatthiasGuelck** [comment]
I use your library in an AWS Lamda function. LD_LIBRARY_PATH is defined there and everything works fine thanks to your solution.
Unfortunately, LD_LIBRARY_PATH is not defined in the Gitlab pipeline for the UnitTests.
I need to find out how the libraries are found there.
So this issue can be closed.
You should consider adding the problem and your solution to the documentation, as not everyone may be aware of this problem.

**Comment by MatthiasGuelck** [comment]
P.S.: ibc.so.6 and libstdc++.so.6  are NOT contained in /myProject/pathToMyLibs
