### ISSUE TITLE
Using wchar_t* as return value of a C++ function on Windows works, but is faulty on Linux

### ISSUE THREAD

**Issue by MatthiasGuelck** [Koromix/koffi#173]
### On Windows, I create a DLL with the following code:
```
#include "pch.h"
extern "C" {
  __declspec(dllexport) const wchar_t* hello(void) {
    const wchar_t * wString = L"Hello from DLL";
    return wString;
  }
}
```

This DLL I use from Typescript like this:
```
import koffi from 'koffi'; 
const lib = koffi.load('hello.dll');
const hello = lib.func('char16_t* hello(void)');
const result = hello();
console.log(result);
```
  
The output is as expected:
`Hello from DLL`

      
### On Linux, I create a Shared Object with the following code:
```
extern "C" {
  const wchar_t* hello(void) {
    const wchar_t * wString = L"Hello from Shared Object";
    return wString;
  }
}
```
        
This Shared Object I use from Typescript like this:
```
import koffi from 'koffi';
const lib = koffi.load('./libHello.so');
const hello = lib.func('char16_t* hello(void)');
const result = hello();
console.log(result);
```
        
The faulty output is:
` H `

So only the first letter is shown on Linux.

The main difference seems to be that on Windows, the characters of the string are 2 bytes long ...

![image](https://github.com/Koromix/koffi/assets/138014262/1f134f19-b923-49fb-9f08-b2753fa6d3c9)

... and on Linux they are 4 bytes long:

![image](https://github.com/Koromix/koffi/assets/138014262/e4c22d4b-4cd6-4c41-96d1-c73ed55bfb37)

If the program code is modified such that a char* is used as a return parameter instead of wchar_t*, everything works as expected.

**Comment by Koromix** [comment]
wchar_t is an abomination (sorry), because it is 2 bytes (char16_t, usually UTF-16) on Windows and 4 bytes (char32_t, UTF-32) on other platforms. It was created even before Unicode 1.0, and it shows.

I haven't implemented support for char32_t, because wchar_t is very rarely used outside of Windows. So is UTF-16, most POSIX platforms prefer `char *` UTF-8 strings.

But I can add it anyway, just in case.

**Comment by MatthiasGuelck** [comment]
"But I can add it anyway, just in case."
 - That would be fantastic!

**Comment by Koromix** [comment]
I've published Koffi 2.9.0-beta.1 with char32_t and wchar_t support.
Install and try with `npm install koffi@beta`.

**Comment by Koromix** [comment]
You probably want to use koffi@2.9.0-beta.2 instead :)

**Comment by Koromix** [comment]
Just tested this on Windows and Linux with Koffi 29.0-beta.2, it works:

```c
// clang -o 173.dll -shared 173.c
// clang -o 173.so -shared 173.c

#include <wchar.h>

#ifdef _WIN32
    #define EXPORT __declspec(dllexport)
#else
    #define EXPORT __attribute__((visibility("default")))
#endif

EXPORT const wchar_t *hello()
{
    const wchar_t *wString = L"Hello from DLL";
    return wString;
}
```

```js
const koffi = require('koffi');

const lib = koffi.load('./173' + koffi.extension);
const hello = lib.func('const wchar_t* hello()');

let msg = hello();
console.log(msg);
```

**Comment by MatthiasGuelck** [comment]
I am currently in the process of adapting my program accordingly.
I'll get back to you with the result.
Many thanks for your great library and your fantastic support.

**Comment by MatthiasGuelck** [comment]
Everything also works perfectly in my test environment (Microsoft Compiler on Windows, g++ on Linux).
Many thanks again.
When will koffi 2.9.0 be available?

**Comment by Koromix** [comment]
Great!
In a day or two if no bug appears ;)

**Comment by MatthiasGuelck** [comment]
Unfortunately I can't find koffi 2.9.0 yet.
Are there any problems?

**Comment by Koromix** [comment]
No reason, it just slipped my mind >< It's released now!
