### ISSUE TITLE
Can I use Koffi with DLL from .NET?

### ISSUE THREAD

**Issue by siriwatknp** [Koromix/koffi#176]
I have a .dll from .Net project that contain class inside a namespace.

Is it possible to use Koffi with this type of DLL?

**Comment by FurryRbl** [comment]
suggestion:
 - https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot
 - https://learn.microsoft.com/en-us/dotnet/core/deploying/native-aot/libraries

Experimental: https://www.npmjs.com/package/node-api-dotnet
