### ISSUE TITLE
char* pointer can't be used as a pointer

### ISSUE THREAD

**Issue by ultimaj** [Koromix/koffi#177]
## Current koffi version

"koffi": "^2.9.0"

## Current Node.js arch

v22.4.1

## Describe your problem in detail

I don't have access to the code of the DLL, but it seems that the functions use the char* as a string (for example the name of the field and its content) and as a real pointer for the message. But here, it seems that the function CreateMessage cast the char* into a string (maybe ?) and can't be use as a pointer. The functions SetField and SendMessage can't work because of that (see the error log).

(The DLL worked with ffi-napi package but I try to migrate to koffi because the library is deprecated now.)

API of the DLL :

char* CreateMessage();
int SetField(char*, char*, char*);
int SendMessage(char*);

```typescript
const lib = koffi.load(lib);

const CreateMessage = lib.func('char* CreateMessage()');
const SetField = lib.func('int SetField(char*, char*, char*)');
const SendMessage = lib.func('int SendMessage(char*)');

const message = CreateMessage();

const result = SetField(message, "FIELD_TEST", "TEST");

// result = -1, can't create the field and add "TEST" inside (1 when it works)

const result_send = SendMessage(message);

// got this error : "Message not found."
```

## What's your expect result

The functions SetField and SendMessage should return 1 to indicate that the field is created and the message is send.

**Comment by Koromix** [comment]
The main problem is that Koffi 2.x automatically converts `(const) char *` result values to JS strings. So the original pointer value is lost. When you can the subsequent functions, Koffi transparently converts back the JS string to a different pointer.

Use a dedicated pointer type, or `void *`, and the pointer value will stay as-is.

```js
const lib = koffi.load(lib);

const CreateMessage = lib.func('void* CreateMessage()');
const SetField = lib.func('int SetField(void*, char*, char*)');
const SendMessage = lib.func('int SendMessage(void*)');

const message = CreateMessage();

const result = SetField(message, "FIELD_TEST", "TEST");

// result = -1, can't create the field and add "TEST" inside (1 when it works)

const result_send = SendMessage(message);

// got this error : "Message not found."
```
