### ISSUE TITLE
What is the correct way to call it?

### ISSUE THREAD

**Issue by wwchao** [Koromix/koffi#178]
libm.func('int utc2bdst(double utc, double bdst[2])')

"What is the correct way to call it?"

**Comment by Koromix** [comment]
I'm guessing bsdt is an output parameter?

If so, something like this should work:

```js
const utc2bdst = lib.func('int utc2bdst(double utc, _Out_ double *bdst)');

let bdst = [0, 0];
let ret = utc2bdst(1723200740, bdst);

console.log(ret, bdst);
```

**Comment by wwchao** [comment]
yes！thanks

**Comment by Koromix** [comment]
For completeness, you can also use Float64Array for bdst, for better performance.

```js
const utc2bdst = lib.func('int utc2bdst(double utc, _Out_ double *bdst)');

let bdst = new Float64Array(2);
let ret = utc2bdst(1723200740, bdst);

console.log(ret, bdst);
```

**Comment by wwchao** [comment]
Thank you. It's very helpful.

**Comment by wwchao** [comment]
Excuse me, I have another question, how to call this function?

My point of doubt is that "OEph* eph" is an output parameter.

bool getEph(OJ2* self, OEph* eph, double startTime, double stopTime, double stepSize, bool useAbsTime = true)

**Comment by Koromix** [comment]
```js
const getEph = lib.func('bool getEph(OJ2* self, _Out_ OEph* eph, double startTime, double stopTime, double stepSize, bool useAbsTime')

let self = { /* stuff */ };
let eph = {};

getEph(self, eph, 0, 12, 1, false);
```

**Comment by wwchao** [comment]
Thanks
