### ISSUE TITLE
Process Exits Without Error Information When Calling DLL Function Using KOFFI

### ISSUE THREAD

**Issue by xiaoshengbao** [Koromix/koffi#179]
Description:

I'm experiencing an issue where my Electron application crashes when calling a function from a DLL using the KOFFI library. Specifically, the process exits immediately when executing const result = R_Card(portBuffer, 1);, and no error messages are shown in the console.

Steps to Reproduce:

1. Initialize the KOFFI library and load the DLL.
2. Define the function signature using koffi.func.
3. Call the DLL function using const result = R_Card(portBuffer, 1);.

```
const koffi = require('koffi');
const path = require('path');

// Load DLL
const rfv2007path = path.resolve('DLL/RFV2007NETHOTEL.dll');
const rfv2007 = koffi.load(rfv2007path);

// Define DLL function
const R_Card = rfv2007.func('__stdcall', 'R_Card', 'string', ['string', 'int']);

// Function that calls DLL function
export const readCardIpc = async (event: any, IntnPort: string) => {
    try {
       const result = R_Card(IntnPort, 1);
        console.log('Result:', result);
        if (result.startsWith('ok')) {
            return result;
        } else if (result === 'ERROR') {
            return 'Failed to read card';
        } else if (result === 'WOFF') {
            return 'Card has been deactivated';
        } else {
            return 'Unknown error';
        }
    } catch (error) {
        console.error('Error calling R_Card function:', error);
        return 'error';
    }
};
```

Expected Behavior:

The process should not exit when calling the DLL function. Instead, the function should return the expected result or an appropriate error message.

Actual Behavior:

The process exits immediately when R_Card is called, and no error messages are logged in the console.

Additional Information:

DLL: RFV2007NETHOTEL.dll
Node.js Version: 20.16.0 (Currently using 32-bit executable)

**Comment by xiaoshengbao** [comment]
[2007hotel.zip](https://github.com/user-attachments/files/16578642/2007hotel.zip)

**Comment by Koromix** [comment]
Did you find the problem? What was it?
