### ISSUE TITLE
Invoking function in the current process

### ISSUE THREAD

**Issue by WillAvudim** [Koromix/koffi#188]
We've been using ffi-napi to invoke prctl on linux (https://man7.org/linux/man-pages/man2/prctl.2.html), which resides in the current process:

```
const syscall = ffi.Library(null, {
  "prctl": ["int32", ["int32", "uint32"]],
})
syscall.prctl(1, 9)
```

As you can see, we are passing **null** as the library location since we would like to connect to the current process instead of opening a library.

How do I achieve the same with koffi? 

I appears that passing null to LoadSharedLibrary() fails with "Unexpected %1 value for filename, expected string or null". Is there a different library call to access the current process? The documentation is silent about this question.

**Comment by Koromix** [comment]
It is supported with null, but the TS definition file did not mention it, the definition was `export function load(path: string): IKoffiLib;`.

I've changed it to `export function load(path: string | null): IKoffiLib;` for the next release.
