### ISSUE TITLE
Property 'alloc' does not exist on type 'typeof import("koffi")'

### ISSUE THREAD

**Issue by gino8080** [Koromix/koffi#189]
I encountered the following TypeScript error while trying to use the `alloc` method from the `koffi` library:

Property ‘alloc’ does not exist on type ‘typeof import(“koffi”)’.

It appears that the TypeScript definitions are missing the `alloc` method, even though it is [documented on the official website](https://koffi.dev/output#stable-pointers). This method should be available in the library, but it is not included in the type definitions.

### Steps to Reproduce:
1. Install the `koffi` library in a TypeScript project.
2. Try to use the `alloc` method, for example:
   ```ts
   import koffi from 'koffi';
   koffi.alloc(1024);
  
3. Observe the TypeScript error indicating that the alloc method does not exist.



### Expected Behavior:

The alloc method should be present in the TypeScript definitions, as it is a valid method according to the official documentation.

### Actual Behavior:

TypeScript throws an error indicating that the alloc method does not exist on the koffi object.

### Suggested Fix:

Add the alloc method to the TypeScript type definitions for koffi.

Environment:

	•	koffi version: 2.9.0
	•	TypeScript version: 5.5.3
	•	Node.js version: 20.x

**Comment by Koromix** [comment]
Indeed, this will be fixed in the next release. Thanks for the report :)
