### ISSUE TITLE
win32 api void *

### ISSUE THREAD

**Issue by EkkoCrystal** [Koromix/koffi#192]
const MapViewOfFile = kernel32.func('__stdcall', 'MapViewOfFile', 'void *', ['void *', 'uint', 'uint', 'uint', 'uint']);
get result: [External: 23e6e600000],How can I resolve this address

**Comment by Koromix** [comment]
Use [koffi.address()](https://koffi.dev/pointers#unwrap-pointers) to extract the address to a BigInt value.

Koffi provides several functions to read from "C" memory or encode JS values to "C" memory, here are the relevant links to the documentation:

- https://koffi.dev/variables#decode-to-js-values
- https://koffi.dev/variables#encode-to-c-memory
-

**Comment by EkkoCrystal** [comment]
Hello, first of all, thank you for your answer.
My requirement is to read data from the shared memory of the window operating system.
This is my code:
const kernel32 = koffi.load('kernel32.dll');
const OpenFileMapping = kernel32.func('__stdcall', 'OpenFileMappingA', 'void *', ['uint', 'int', 'str']);
const MapViewOfFile = kernel32.func('__stdcall', 'MapViewOfFile', 'int *', ['void *', 'uint', 'uint', 'uint', 'uint']);
const UnmapViewOfFile = kernel32.func('__stdcall', 'UnmapViewOfFile', 'bool', ['void *']);
const CloseHandle = kernel32.func('__stdcall', 'CloseHandle', 'bool', ['void *']);


const mmf = OpenFileMapping(FILE_MAP_ALL_ACCESS, TRUE, "CameraSharedMemory");
if (mmf === null) {
&nbsp; &nbsp; throw new Error("Could not open shared memory.");
}


const view = MapViewOfFile(mmf, FILE_MAP_READ, 0, 0, 1024);
if (view === null) {
&nbsp; &nbsp;throw new Error("Could not map view of file.");
}
const viewAddress = koffi.address(view)


At this time, the result is: 2113557102592n, and then I don't know what to do.
According to your guidance, I tried:
const buffer1 = koffi.decode(viewAddress, 'int', 5);
It still doesn't work. I hope to get guidance. Thank you very much







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Koromix/koffi"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月13日(星期五) 下午5:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Koromix/koffi] win32 api void * (Issue #192)





 
Use koffi.address() to extract the address to a BigInt value.
 
Koffi provides several functions to read from "C" memory or encode JS values to "C" memory, here are the relevant links to the documentation:
  
https://koffi.dev/variables#decode-to-js-values
 
https://koffi.dev/variables#encode-to-c-memory
