### ISSUE TITLE
Load multiple libraries

### ISSUE THREAD

**Issue by AntonK93** [Koromix/koffi#193]
Trying to load two libraries at once and then use their functions, currently looks pretty simple
```
    private WNScan = koffi.load('hardware-api/omr-scanner/WNScanDll_A6.so');
    private WT_IsDevice = this.WNScan.func('WT_IsDevice', 'int', []);
    private WT_DeviceOpen = this.WNScan.func('WT_DeviceOpen', 'int', []);
    private WT_DeviceClose = this.WNScan.func('WT_DeviceClose', 'int', []);
    private WT_ScannerOn = this.WNScan.func('WT_ScannerOn', 'int', []);
    private WT_ScannerOff = this.WNScan.func('WT_ScannerOff', 'int', []);
    private WT_IsPaper = this.WNScan.func('WT_ScannerOff', 'int', ['int']);
    private WT_BarcodeScanSelectBuf = this.WNScan.func('WT_BarcodeScanSelectBuf', 'int', [imgStruct, imgStruct, 'int', 'int']);
    private WT_SetLineNumber = this.WNScan.func('WT_SetLineNumber', 'int', ['int']);
    private WT_SetPixelDataSize = this.WNScan.func('WT_SetPixelDataSize', 'int', ['int']);
    private WT_SetMotorDir = this.WNScan.func('WT_SetMotorDir', 'int', ['int']);

    private WOMR = koffi.load('hardware-api/omr-scanner/WOMRDll_A6.so');
    private SetConfig = this.WOMR.func('SetConfig', 'int', ['char *']);
    private WOMR_CropImage = this.WOMR.func('WOMR_CropImage', 'int', [imgStruct, 'int', imgStruct, imgStruct]);
    private ResultImageBuf = this.WOMR.func('ResultImageBuf', 'int', [imgStruct, imgStruct, 'int', 'char *', 'int *', 'int *', 'int *']);
    private GetResultData = this.WOMR.func('GetResultData', 'int', ['int', 'char *', 'int *']);
```
Problem is that after loading the first one lib it fails with second telling that `Error: Failed to load shared library: libtiff.so.5: cannot open shared object file: No such file or directory`

I believe i'm missing the point how to do that properly but didn't find any alternative. Ty in advance

**Comment by AntonK93** [comment]
Ok my bad, it can't load that second lib at all despite the fact it was working with ffi-napi. But still maybe something specified wrongly?

**Comment by AntonK93** [comment]
The previous implementation
```
    private WNScan = new Library('hardware-api/omr-scanner/WNScanDll_A6', {
        WT_IsDevice: ['int', []],
        WT_DeviceOpen: ['int', []],
        WT_DeviceClose: ['int', []],
        WT_ScannerOn: ['int', []],
        WT_ScannerOff: ['int', []],
        WT_IsPaper: ['int', [ref.refType('int')]],
        WT_BarcodeScanSelectBuf: ['int', [ref.refType(imgStruct), ref.refType(imgStruct), 'int', 'int']],
        WT_SetLineNumber: ['int', ['int']],
        WT_SetPixelDataSize: ['int', ['int']],
        WT_SetMotorDir: ['int', ['int']],
    });

    private WOMR = new Library('hardware-api/omr-scanner/WOMRDll_A6', {
        SetConfig: ['int', [ref.refType('char *')]],
        WOMR_CropImage: ['int', [ref.refType(imgStruct), 'int', ref.refType(imgStruct), ref.refType(imgStruct)]],
        ResultImageBuf: [
            'int',
            [
                ref.refType(imgStruct),
                ref.refType(imgStruct),
                'int',
                ref.refType('char *'),
                ref.refType('int *'),
                ref.refType('int *'),
                ref.refType('int *'),
            ],
        ],
        GetResultData: ['int', ['int', ref.refType('char *'), ref.refType('int *')]],
    });
```

**Comment by AntonK93** [comment]
also that's not the path/bundles issue since the libraries not in the dist folder and one of them works, really can't get what's wrong with second one

**Comment by Koromix** [comment]
Hi, could you send me the shared libraries? At least WNScanDll_A6, WOMRDll_A6 and the libraries they depend upon?

To niels.martignene@protopnmail.com if you can't post it here :)

**Comment by AntonK93** [comment]
@Koromix sent you both of the libs, they do not depend on anything, just a hardware for specific printer, good enough to get access to their functions through the koffi

**Comment by AntonK93** [comment]
@Koromix Hey got any luck with these libs ?

**Comment by Koromix** [comment]
On my system it fails simply because `libtiff.so.5` does not exist anymore.

However symlinking `/usr/lib/x86_64-linux-gnu/libtiff.so.5` to `/usr/lib/x86_64-linux-gnu/libtiff.so.6`.

This does not seem related to Koffi, but is simply an ABI issue. Does it work on ffi-napi on the exact same system?

**Comment by AntonK93** [comment]
@Koromix great that was the issue! my bad that i didn't research the libtiff.so.5 itself which was absent in the OS, in my case there was no 5 nor 6 version, so the `apt install -y libtiff5` has solved my problem :) 
Regarding your question about the system that was the case as well, so we did an update of dockerfile with a modern one image `Debian GNU/Linux 11 (bullseye)` to start using updated node version and so on but ffi-napi doesn't work there so we have switched to the koffi and that lib thing appeared.

But thank you again for solving up the issue !
