### ISSUE TITLE
[koffi] Reducing size of binary/npm package

### ISSUE THREAD

**Issue by Septh** [Koromix/koffi#201]
Hi,

I'm using Koffi to build [libwin32](https://github.com/Septh/libwin32) and so far everything is working fine -Koffi makes this a breeze, many thanks for the great work!

My only concern is about the size of the Koffi binary: 2.23Mb for the win32-x64 binary alone seems quite a lot considering the code base is rather small. While I successfully built Koffi from sources, I have very little knowledge of the C++ build tools and I couldn't find a way to get a lighter binary. Would you have any advice here?

Also, would you consider exploring the possibility to publish multiple npm packages -one per platform/arch build- instead of a single, monolithic package? This would save bandwidth and time to users. [Rollup](https://github.com/rollup/rollup) and [esbuild](https://github.com/evanw/esbuild) are two examples of popular npm packages with native code distributed this way:

https://www.npmjs.com/package/@rollup/rollup-linux-x64-gnu
https://www.npmjs.com/package/@rollup/rollup-win32-x64-msvc
etc.

Thanks!

**Comment by Koromix** [comment]
While it does not fundamentally change things, I've made several changes to reduce the size of Koffi, both the binaries and the package as a whole.

Now, in Koffi 2.16.0 (which I've just released), the uncompressed package weighs 28.7 MB and the tarball is 7.0 MB. That's a substantial improvement from Koffi 2.14 (86 MB uncompressed, 16.8 MB compressed).

This probably does not change things for you, but you can fix the stat in the koffi-cream README, which says "As of 2.14.0, Koffi weights 16.9 MB compressed and 86 MB uncompressed" :)

**Comment by Septh** [comment]
Oh crap, I missed that release 😬 

> Now, in Koffi 2.16.0 (which I've just released), the uncompressed package weighs 28.7 MB and the tarball is 7.0 MB. That's a substantial improvement from Koffi 2.14 (86 MB uncompressed, 16.8 MB compressed).

Well done! This is definitely a huge improvement IMHO! 👍 

> This probably does not change things for you, but you can fix the stat in the koffi-cream README, which 
says "As of 2.14.0, Koffi weights 16.9 MB compressed and 86 MB uncompressed" :)

Of course. I've been short on time lately but will do ASAP. 

Congrats again!

**Comment by Septh** [comment]
Done ;)

https://github.com/Septh/koffi-cream/blob/main/packages/koffi-cream/README.md

**Comment by Koromix** [comment]
Good! Sorry though, there's already a new version, Koffi 2.16.1 :)
https://koffi.dev/changelog

**Comment by Koromix** [comment]
Though to be fair, the TypeScript 6.0 compiler is in JavaScript/TypeScript, so it does not embed any binaries ;) Makes it easier to be small!

TypeScript 7.0 is implemented in Go instead, and each binary weighs more than 20 Mb. OTOH they ship the binaries in separate packages.

**Comment by Septh** [comment]
> Though to be fair, the TypeScript 6.0 compiler is in JavaScript/TypeScript, so it does not embed any binaries ;) Makes it easier to be small!

Indeed :) I couldn't resist the nod to TypeScript, but if you find it offending I'll be happy to remove it. Just tell me.

> Good! Sorry though, there's already a new version, Koffi 2.16.1 :) https://koffi.dev/changelog

Thank you. I usually check for new versions once a day but there are times where I may have to wait a couple of days. Syncing koffi-cream with Koffi is still a manual operation; I should probably explore a way to automate this :)

**Comment by Koromix** [comment]
No it's okay ;)

2.x releases will calm down soon. Some recent changes (such as the *Fix "IsOnCentralStack()" assertion/crash when using callbacks in recent Node versions* in Koffi 2.15.3) caused new bugs, especially for callbacks, but it's getting there.

Then it will be time for Koffi 3.0, which is quite a bit faster and has less overhead, but with some (mostly one but still) API changes. And I will maybe switch to split packages, but I'm not sure. I still don't like it but others do... :)

**Comment by Septh** [comment]
> Then it will be time for Koffi 3.0, which is quite a bit faster and has less overhead

Can't wait! 👍 

> And I will maybe switch to split packages, but I'm not sure. I still don't like it but others do... :)

Yeah, I saw a while ago in your source code that you made provisions for this. Honestly, I am **not** the one who will tell you not to do it :)

**Comment by Koromix** [comment]
You can test `koffi@3.0.0-alpha.1` if you want ;)

The main API change is that pointers are now BigInt values (instead of V8 external objects), for performance. Most code should work as-is though.

**Comment by Koromix** [comment]
Koffi 3 is out, and uses split packages ;)

**Comment by Septh** [comment]
Then I think this means the end for koffi-cream :)

I already made an announcement in the README for 2.16.2, I'll update it shortly to make it clear the time has come. 👍 


> and uses split packages ;)

I appreciate how difficult it must have been for you to make this choice. Thank you so much. 🙏

**Comment by Koromix** [comment]
Some fights just aren't worth the trouble 🙂

**Comment by Koromix** [comment]
I might release Koffi 2.17 at some point, with some of the performance changes (those that are not API-breaking) from Koffi 3.

It will still be monolithic, so might have to make a few more releases ;)
