### ISSUE TITLE
Wrong string length when using wcslen() in a Linux shared object

### ISSUE THREAD

**Issue by MatthiasGuelck** [Koromix/koffi#202]
In July, with version 2.9.0, you added support for “wchar_t” for me.
Thanks again for that.
Unfortunately, using Koffi 2.9.1 I have now noticed an error that occurs when using the function “wcslen()” in a Linux shared object.
Under certain circumstances, the wrong number of characters is determined.
With a Windows DLL that uses the same code, the error does not occur.
If I call the Linux shared object from Python, I also get the correct output under Linux.

If I use the following code ...

mylib.cpp
```
#include <cwchar>  // for wcslen
// g++ -shared -fPIC -o mylib.so mylib.cpp
extern "C" {
    size_t getWCharLength(const wchar_t* str) {
        return wcslen(str);
    }
}
```

test.ts
```
import { load } from 'koffi';

describe("Test", () => {

    it("wcslen", async () => {    
        
        const mylib = load('mylib.so');
        const getWCharLength = mylib.func('size_t getWCharLength(const wchar_t* str)');
         
        let compare = (path:string) => console.log(`${path.length === getWCharLength(path) ? "\x1b[32m" : "\x1b[31m"}ts:${path.length} so:${getWCharLength(path)} \x1b[37m${path}`);

        compare("");
        let acc = ""
        for (let i=0; i<32; i++) {
            acc+=0
            compare(acc)
        }
    });
});
```

... I get the following output:

![image](https://github.com/user-attachments/assets/3c3b8335-08c7-4014-b951-4adda9b23af7)

**Comment by Koromix** [comment]
Indeed, I just found the cause of this issue. I will make a release tomorrow (can't make it right now).

**Comment by MatthiasGuelck** [comment]
Thank you for the very quick response.
Do you have any idea when there will be a new version?

**Comment by MatthiasGuelck** [comment]
Thank you for fixing the bug so quickly.

**Comment by MatthiasGuelck** [comment]
Many thanks for this.
I will test the new version in the next few days.

**Comment by MatthiasGuelck** [comment]
I have reviewed the new version and am once again extremely impressed by the speed with which you fix bugs.
