### ISSUE TITLE
Example with yao-pkg?

### ISSUE THREAD

**Issue by sigmama** [Koromix/koffi#209]
Hi @Koromix , first of all, thanks for provide this lib. I started to research on this lib when the node-ffi-napi is no longer available after node 16.

I'm trying to use it with native dll like user32.dll. Below is a simple function to shutdown a windows 11 machine.

```
import koffi from 'koffi';

export function shutdownWindows(): void {
  const wLib = koffi.load('user32.dll');
  const wShutdown = wLib.func('ExitWindowsEx', 'bool', ['uint32', 'uint32']);
  const EWX_SHUTDOWN = 0x00000001;
  const EWX_FORCE = 0x00000004;
  const result = wShutdown(EWX_SHUTDOWN | EWX_FORCE, 0);
  if (!result) {
    throw new Error('Failed to shutdown with native windows api');
  }
}
```

I've verified above code works in the pure node environment.
But after I bundled the code with [pkg](https://github.com/yao-pkg/pkg) into an exe file, the function no longer works.
So would you mind to check whether it is feasible to use pkg with koffi? Or any other advice?

**Comment by Koromix** [comment]
I made an example here: https://koffi.dev/packaging#node-js-and-yao-pkg

**Comment by sigmama** [comment]
Hi, I believe the issue is not related koffi itself, so I would close this issue.

I've verified that the sample code below works with pkg. The issue shall be related to ExitWindowsEx which is a low level system api. After bundled, the call is blocked.
```
// ES6 syntax: import koffi from 'koffi';
const koffi = require('koffi');

const lib = koffi.load('user32.dll');

// The following two declarations are equivalent, and use stdcall on x86 (and the default ABI on other platforms)
const MessageBoxA_1 = lib.func('__stdcall', 'MessageBoxA', 'int', ['void *', 'str', 'str', 'uint']);
const MessageBoxA_2 = lib.func('int __stdcall MessageBoxA(void *hwnd, str text, str caption, uint type)');
```
