### ISSUE TITLE
How to handle circular dependencies that C solves with forward declarations?

### ISSUE THREAD

**Issue by anyc** [Koromix/koffi#213]
Hello,

I have a C header with a construct like the following:
```
struct my_struct;
typedef void (*my_type)(struct my_struct *);
struct my_struct {
  my_type my_fct_ptr;
};
```
If I create the typedef and struct with koffi, I get an "Unknown or invalid type name" error as `my_struct` is not defined when I call `koffi.proto()` for `my_type`.

If I try to call `koffi.proto` for `my_type` inside the struct, I get the same error. Anyways, this would only work in my case if `my_type` is only used once.

I also tried to create `my_struct` as opaque type first, but then get a "Duplicate type name" error.

Is there a way to solve this? If not, I guess allowing a opaque type to be replaced might be a viable way to solve this.

Thank you!

**Comment by anyc** [comment]
By the way, I also wrote a wrapper for Python with ctypes. There, I was able to create `my_struct` without members first and then add the members after I created the function pointer type. Maybe something like this would be possible here, too?

**Comment by Koromix** [comment]
You can now solve this problem with Koffi 2.10.0, which allows an opaque type to be redefined to a concrete struct or union type.

The documentation to do so is here: https://koffi.dev/misc#circular-references
