### ISSUE TITLE
[koffi] Usage with Jest

### ISSUE THREAD

**Issue by CommandMC** [Koromix/koffi#4]
Hello there! I'm trying to use Koffi together with [Jest](https://jestjs.io), but it seems like Jest is keeping some sort of module state alive between tests, causing aliased types to stay defined after a test is done running.
I'm suspecting that this is caused by Jest re-using one Node process for multiple tests

For more details on how exactly I'm using Koffi (and Jest), see https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/pull/2717
I haven't setup a minimal reproducible example yet, if that would make it easier, let me know

**Comment by Koromix** [comment]
You can use [koffi.reset()](https://koffi.dev/misc#reset-internal-state) now, in Koffi 2.5.19.
