### ISSUE TITLE
Error: Failed to load shared library: %1 is not a valid Win32 application while loading library

### ISSUE THREAD

**Issue by hendrikunger** [Koromix/koffi#55]
Hi there,
I am trying to load a library provided by the company Mahr to interact with their measurement devices.
I am using Windows 10 x64 and node.js v18.17.0 also x64

The code

```
var koffi = require('koffi');
const n1700 = koffi.load("N1700_64");
```

fails with

Error: Failed to load shared library: %1 is not a valid Win32 application.
    at Object.<anonymous> (c:\Users\unhe\GitRepos\node-red-contrib-milimar-N-1701\test.js:2:21)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47

This happens with the Win32 and Win64 Versions of the library. 

I know the library has an dependency on an other library ftd2xx.dll, which I copied to the same location as the N1700_64.dll. Does koffi support this use case, or could this be the issue? 
Is there anything else I could try?  I was able to run your example, as well loading a small toy library I compiled myself.

The library can be obtained under https://metrology.mahr.com/de/produkte/artikel/5331130-usb-anschlussmodul-millimar-n-1701-usb/
at the bottom of the page under Download/Software
Direct Link: https://metrology.mahr.com/fileadmin/assets/files/Millimar--N1700--SW--NA--2022-04-14--V1_02-11.zip

**Comment by Koromix** [comment]
I just tested and was able to load it.

The ftd2xx.dll I found in the archive is for Windows 32-bit, so I used Node 32-bit (if you use Node 64-bit it won't work) with the 32-bit N1700.dll and ftd2xx.dll.

The binaries for Node 32-bit are here:

- Installer: https://nodejs.org/dist/v18.17.0/node-v18.17.0-x86.msi
- ZIP: https://nodejs.org/dist/v18.17.0/node-v18.17.0-win-x86.zip

**Comment by hendrikunger** [comment]
Oh thank you for your quick response and help. 
I got the ftd2xx.dll as a 64 bit version from FTDI from https://ftdichip.com/drivers/d2xx-drivers/ but this did not work either. So dll I am trying to load seems to have even more 32bit dependencies. 

So the error is clearly on my side, sorry for bothering you and thanks for your help and the great library.

**Comment by Koromix** [comment]
This tool can help you: https://github.com/lucasg/Dependencies

Use the DependenciesGui.exe tool to list the dependencies, including missing ones which will show up with a "?" symbol :)

**Comment by zhouJiecode** [comment]
@Koromix i have the problem
![image](https://github.com/Koromix/koffi/assets/11864722/6559208b-0d31-41b5-b92e-ae9a4bf6556b)


i use vlc.dll with koffi in electron

> "electron": "17.4.11"
> "koffi": "^2.5.20"

vlc.dll is from http://download.videolan.org/pub/videolan/vlc/3.0.18/win32/
![image](https://github.com/Koromix/koffi/assets/11864722/dec746a4-9436-4f3e-a0e4-91451fa253f8)

could you help me please

**Comment by Koromix** [comment]
I'm pretty sure you're using Node 64-bit, while this VLC dll is 32-bit.

You can find 64-bit builds of VLC here: https://download.videolan.org/pub/videolan/vlc/3.0.18/win64/
Or use Node 32-bit, it would work too.
