### ISSUE TITLE
Add dates to changelog

### ISSUE THREAD

**Issue by Pomax** [Koromix/koffi#59]
The changelog only has version numbers, rather than also showing the release date for each version. Since  you're using a monorepo instead of a dedicated repo with easily checked tags to tell folks when a specific version was release, so they can see whether or not the project has been abandoned or not (RIP ffi and neon) it is pretty important to have dates in the changelog.

**Comment by Koromix** [comment]
Good idea, the changelog now has dates :)

**Comment by Pomax** [comment]
awesome, thanks!
