### ISSUE TITLE
[koffi] when passing nested prop of object as void*, the rest of the object does not pass properly

### ISSUE THREAD

**Issue by idoavni99** [Koromix/koffi#6]
I'm defining the following types:
struct('Cam', {
  location: 'void*',
  orientation: 'Euler',
  fovX: 'double',
  fovY: 'double',
  pixelsX: 'int',
  pixelsY: 'int',
});

struct('geoPoint', {
  projection: 'int',
  values: struct({
    geo: struct({ lat: 'double', lon: 'double', alt: 'double' }),
  }),
});

Receving a complete object with all properties via rest API.
afterwards, I call these lines of code;
body.cam.location = koffi.as(cam.location, "geoPoint").

Then, i'm sending body.cam as a parameter to a function defined like this: Cam* cam
The input: 
{"camera":{"location":{"projection":9,"values":{"vec":[73.4747,34.26544,85.712343]}},"orientation":{"azimuth":76.1212,"roll":23.121,"pitch":87.2112},"fovX":81.1212,"fovY":93.1234,"pixelsX":143,"pixelsY":231}}

The input in C++:
camX: 76.121200, camY: 87.211200, camZ: 23.121000,
camFovX: 0.000000, camFovY: 0.000000
pixX: 0.000000, pixY: -0.000000

**Comment by Koromix** [comment]
There have been a few ABI fixes since you made this post; does it work now?

If not, could you post show original C types and C function prototypes?

**Comment by idoavni99** [comment]
It's not relevant anymore. Thank you
