### ISSUE TITLE
"TypeError: Unexpected <type_41> * value" occurs when upgrading from koffi 2.5.3 to 2.5.4

### ISSUE THREAD

**Issue by wanglin86769** [Koromix/koffi#62]
I have the following code which works with koffi 2.5.3 but throws error when executing **ca_field_type()** function from koffi 2.5.4,

```
let chanId = koffi.pointer('chanId', koffi.opaque());
const ca_field_type = libca.func('ca_field_type', 'short', [chanId]);

let chidPtr = [null];
let errCode = ca_create_channel(this.pvName, callback, null, priority, chidPtr);
this.chanId = chidPtr[0];
this.fieldType = ca_field_type(this.chanId);
```

It seems that my usage works for 2.5.3 but is not compatible with 2.5.4. How can I fix it?

![7dd355070bd58a2cefda1e7eb9ae40d](https://github.com/Koromix/koffi/assets/62229607/9832c4d9-2cf6-4502-a322-1c79a0722721)

**Comment by Koromix** [comment]
I looked at your code, you should change the declaration of `ca_create_channel`.

Right now it looks like this:

```js
let pointer = koffi.pointer('pointer', koffi.opaque(), 2);
let chanId = koffi.pointer('chanId', koffi.opaque());

// ...

const ca_create_channel = libca.func('ca_create_channel', 'int', ['string',koffi.pointer(ConnectionCallback),'pointer','int',koffi.out(pointer)]);
```

But if ca_create_channel gives you a chanId then it should be something like this instead:

```js
let chanId = koffi.pointer('chanId', koffi.opaque());

// ...

const ca_create_channel = libca.func('ca_create_channel', 'int', ['string',koffi.pointer(ConnectionCallback),'void *','int',koffi.out(koffi.pointer(chanId))]);
```

**Comment by Koromix** [comment]
This is a good example of the limitations of semantic versioning, because 2.5.4 fixes a bug in Koffi, but this breaks your previously working code in the process :p

**Comment by Koromix** [comment]
No problem, thank you :)
