### ISSUE TITLE
koffi integration issue in Nw.js

### ISSUE THREAD

**Issue by KevinMazelin** [Koromix/koffi#64]
Hello  ! 
I need help integrating koffi into nw.js.
When I take the example project [here](https://github.com/Koromix/rygel/tree/master/src/koffi/examples/nwjs),
The require .node file call is problematic in index.js from koffi. I think the path is correct because i can log package file in nw.js.

'Error: a link library initialization routine
dynamics (DLL) failed.'

I tried several version of nw.js SDK, 0.75 0.78 0.77.
My dll that I want to load is 32 bit.
Currently I also tried Nodes.js 18 and 20.51 in x86 and x64 version.
on Windows 10. 

Could someone help me figure out what's wrong?

When I use koffi with nodejs x86 I manage to load my dll but not with Nw.js.

Sincerely,

**Comment by Koromix** [comment]
Try with Koffi 2.5.14 which I've just released :)
