### ISSUE TITLE
Error 1114 when loading win32_x64\koffi.node

### ISSUE THREAD

**Issue by hiniestic** [Koromix/koffi#65]
I get error 1114 when loading win32_x64\koffi.node. Path is correct.

I have also try to build the project, to check if is a build issue and I get:

C:\Users\usuario\Downloads\prueba\github\rygel-master\src\koffi\test\union.c(121,49): warning C4244: 'return': conversi
ón de 'double' a 'float'; posible pérdida de datos [C:\Users\usuario\Downloads\prueba\github\rygel-master\src\koffi\tes
t\build\v18.17.0_x64\union.vcxproj]
C:\Users\usuario\Downloads\prueba\github\rygel-master\src\koffi\test\union.c(122,51): warning C4244: 'return': conversi
ón de 'uint64_t' a 'float'; posible pérdida de datos [C:\Users\usuario\Downloads\prueba\github\rygel-master\src\koffi\t
est\build\v18.17.0_x64\union.vcxproj]
     Creando biblioteca C:/Users/usuario/Downloads/prueba/github/rygel-master/src/koffi/test/build/union.lib y objeto C
  :/Users/usuario/Downloads/prueba/github/rygel-master/src/koffi/test/build/union.exp
  union.vcxproj -> C:\Users\usuario\Downloads\prueba\github\rygel-master\src\koffi\test\build\union.dll
  Building Custom Rule C:/Users/usuario/Downloads/prueba/github/rygel-master/src/koffi/test/CMakeLists.txt
  win32.c
     Creando biblioteca C:/Users/usuario/Downloads/prueba/github/rygel-master/src/koffi/test/build/win32.lib y objeto C
  :/Users/usuario/Downloads/prueba/github/rygel-master/src/koffi/test/build/win32.exp
  win32.vcxproj -> C:\Users\usuario\Downloads\prueba\github\rygel-master\src\koffi\test\build\win32.dll
Error: Failed to run build step
    at Builder.build (C:\Users\usuario\Downloads\prueba\github\rygel-master\src\cnoke\src\builder.js:253:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (C:\Users\usuario\Downloads\prueba\github\rygel-master\src\cnoke\cnoke.js:135:9)

**Comment by Koromix** [comment]
Can you try again with Koffi 2.5.18?

**Comment by hiniestic** [comment]
Works great!
