### ISSUE TITLE
Koffi leaves open async handles on exit

### ISSUE THREAD

**Issue by TheCleric** [Koromix/koffi#67]
When running koffi in my project, jest (with the `--detectOpenHandles` option) throws the following error:

```
Jest has detected the following 1 open handle potentially keeping Jest from exiting:

  ●  Koffi Async Callback Broker

       5 | Object.defineProperty(exports, "__esModule", { value: true });
       6 | exports.noop = void 0;
    >  7 | const koffi_1 = __importDefault(require("koffi"));
         |                                 ^
       8 | const test = koffi_1.default.types;
       9 | const noop = () => {
      10 |     console.log({ test });

      at Runtime._loadModule (node_modules/jest-runtime/build/index.js:1009:29)
      at Object.<anonymous> (node_modules/koffi/src/index.js:48:41)
      at Object.<anonymous> (dist/index.js:7:33)
      at Object.<anonymous> (dist/index.test.js:3:12)
```

I have created a minimal reproducible example in this repo:

https://github.com/TheCleric/koffi-open-handle-demo

**Comment by Koromix** [comment]
This handle gets closed correctly once Node unloads Koffi, at the very end.
Is it a problem that it does not get freed earlier? Does it actually prevent something from exiting?

**Comment by TheCleric** [comment]
It causes issues with using Jest to test code that uses Koffi as this is an error when using `--detectOpenHandles` to ensure all promises are handled correctly.

**Comment by Koromix** [comment]
This should be improved in Koffi 2.5.19.

If you don't use callbacks, the async thread broker is not created.

If a callbacks gets used, you can use [koffi.reset()](https://koffi.dev/misc#reset-internal-state) to drop the handle.

**Comment by TheCleric** [comment]
Thanks!
