### ISSUE TITLE
Call failed in vscode extension

### ISSUE THREAD

**Issue by 1234567845246** [Koromix/koffi#68]
Hi, I need to use some dynamic libraries I have already written for vscode extension, But he reported an error：
koffi requires Node >= 14.17.0 in the Node 14.x branch (N-API >= 8).
But I was able to run it under normal conditions, and node = 18.12,

**Comment by liqianglai** [comment]
I have the same question

**Comment by Koromix** [comment]
I'll need more info to see this through.
I just made a basic Hello World extension, loaded koffi and it worked.

Can you show some code or a way to reproduce?

**Comment by 1234567845246** [comment]
Hello, I have solved this problem. Because there is a node inside vscode, the third-party library we use is actually the node running in it, which has nothing to do with your local node environment. I was vscode 1.65 at that time, and the node in it is 14.x, so an error was reported. Thank you for your answer

**Comment by Koromix** [comment]
Thanks :)
