### ISSUE TITLE
[koffi] Cannot use more than 32 output parameters

### ISSUE THREAD

**Issue by vickp** [Koromix/koffi#69]
I'm trying to use Koffi to call a function from a DLL Payment library.

Unfortunately, I don't have control over this function, and it's designed to accept 36 output variables as parameters. 

I saw an error message: 

`TypeError: Functions cannot have more than 32 parameters`

Is there any way to potentially bypass, raise, or customize this restriction?

Thanks for your help!

**Comment by Koromix** [comment]
I've raised the limit to 64 in Koffi 2.5.12 :)
