### ISSUE TITLE
latest Koffi version 2.5.13 throwing Mismatched native Koffi modules error

### ISSUE THREAD

**Issue by caseymia** [Koromix/koffi#70]
I think there must be some versioning issue with the latest Koffi module published, because I keep getting `Error: Mismatched native Koffi modules` when I try to use it. The native version is 2.5.12 and the package version is 2.5.13... any help here? Thanks 🙏

**Comment by Koromix** [comment]
My fault, should be fixed in Koffi 2.5.14 which I've just released :)
