### ISSUE TITLE
npm install koffi occure error

### ISSUE THREAD

**Issue by xiaxuanlii** [Koromix/koffi#72]
when I npm install koffi, it occure a error:
npm ERR! code 1
npm ERR! path E:\self_Project\use-electron-vite\node_modules\koffi        
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node src/cnoke/cnoke.js --prebuild -d src/koffi
npm ERR! Error: CMake does not seem to be available
npm ERR!     at check_cmake (E:\self_Project\use-electron-vite\node_modules\koffi\src\cnoke\src\builder.js:380:27)
npm ERR!     at Builder.build (E:\self_Project\use-electron-vite\node_modules\koffi\src\cnoke\src\builder.js:229:9)
npm ERR!     at async main (E:\self_Project\use-electron-vite\node_modules\koffi\src\cnoke\cnoke.js:140:9)

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Local\npm-cache\_logs\2023-08-25T09_54_24_639Z-debug-0.log

I don't kown why happen this situation.
And I copy other's node_modules's koffi file into my node_modules, It OK

**Comment by Koromix** [comment]
Should be fixed in Koffi 2.5.16 :)
