### ISSUE TITLE
Bool value not passed to a function

### ISSUE THREAD

**Issue by hiniestic** [Koromix/koffi#75]
I have a JAVA app working with a DLL that has this funcion:

```
public int ShowHideWindow(boolean flag) {
		return c_ShowHideWindow(flag);
}
```
and works great ShowHideWindow(true) and ShowHideWindow(false)

I have set up with Koffi the same function:

`const ShowHideWindow= MyDLL.func('int Java_c_1ShowHideWindow(bool)');
`    

But this doesn't work, even if I try ShowHideWindow(true) or ShowHideWindow(false) always false value is pass to the DLL funcion.
I have also try to setup the function as:

`const ShowHideWindow=  MyDLL.func('Java_c_1ShowHideWindow, int, [bool]');`

but same issue.

Thanks!

**Comment by Koromix** [comment]
Okay, I know what's going on. A simple disassembly of the function shows that it reads the third parameter (CPU register r8, Windows 64 ABI) for the bool.

This is because the functions you're calling are actually Java native methods. The `native int c_ShowHideWindow(boolean flag);` Java declaration actually looks something like this in C:

```c
JNIEXPORT int JNICALL Java_PlanCad_PlanCadApi_c_1ShowHideWindow(JNIEnv *env, jobject obj, bool flag)
{
    // Show or hide depending on flag
}
```

Obviously Node.js is not Java so we don't have anything useful to give for the first two parameters (JNIEnv and the object for which the method is called).

But in this case, it does not look like your DLL uses the first two parameters for anything so we can just set them to 0 and it works.

So in your case, this will work:

```js
const koffi = require('koffi');
const path = require('path');

const PlanCADAPI = koffi.load('PlanCADAPI.dll');

// Use dummy int for the first two native Java parameters (env and obj)
const OpenCommunication = PlanCADAPI.func('int Java_PlanCad_PlanCadApi_c_1OpenCommunication(int, int)');
const ShowHideWindow = PlanCADAPI.func('int Java_PlanCad_PlanCadApi_c_1ShowHideWindow(int, int, bool)');

console.log("Init communication");
let connectionResult = OpenCommunication(0, 0);
setTimeout(function() {
    checkConnection();
}, 2000);

function checkConnection() {
    if (connectionResult == '0') {
        console.log("Comunication open");
        console.log("Opening the windows. Payload should be ShowWindow and not HidenWindow");
        console.log(ShowHideWindow(0, 0, true));
    } else {
        setTimeout(function() {
            if (connectionResult == 5) {
                console.log("Connection error. Please restart app");
            } else {
                checkConnection();
            }
        }, 2000);
    }
}
```

**Comment by Koromix** [comment]
You can make the calls a bit less ugly with something like this:

```js
const koffi = require('koffi');
const path = require('path');
const PlanCADAPI = koffi.load('PlanCADAPI.dll');
const OpenCommunication = wrapJavaMethod(PlanCADAPI, 'int Java_PlanCad_PlanCadApi_c_1OpenCommunication(int, int)');
const ShowHideWindow = wrapJavaMethod(PlanCADAPI, 'int Java_PlanCad_PlanCadApi_c_1ShowHideWindow(int, int, bool)');

console.log("Init communication");
let connectionResult = OpenCommunication();
setTimeout(function() {
    checkConnection();
}, 2000);

function checkConnection() {
    if (connectionResult == '0') {
        console.log("Comunication open");
        console.log("Opening the windows. Payload should be ShowWindow and not HidenWindow");
        console.log(ShowHideWindow(true));
    } else {
        setTimeout(function() {
            if (connectionResult == 5){
                console.log("Connection error. Please restart app");
            } else {
                checkConnection();
            }
        }, 2000);
    }
}

function wrapJavaMethod(lib, definition) {
    let func = lib.func(definition);
    return (...args) => func(0, 0, ...args);
}
```

**Comment by hiniestic** [comment]
Thanks very much for your support!!!Regards,AlejandroEnviado desde mi iPhoneEl 1 sept 2023, a las 7:57, Niels Martignène ***@***.***> escribió:﻿
Okay, I know what's going on. A simple disassembly of the function shows that it reads the third parameter (CPU register r8, Windows 64 ABI) for the bool.
This is because the functions you're calling are actually Java native methods. The native int c_ShowHideWindow(boolean flag); Java declaration actually looks something like this in C:
JNIEXPORT int JNICALL Java_PlanCad_PlanCadApi_c_1ShowHideWindow(JNIEnv *env, jobject obj, bool flag)
{
    // Show or hide depending on flag
}
Obviously Node.js is not Java so we don't have anything useful to give for the first two parameters (JNIEnv and the object for which the method is called).
But in this case, it does not look like your DLL uses the first two parameters for anything so we can just set them to 0 and it works.
So in your case, this will work:
const koffi = require('koffi');
const path = require('path');

const PlanCADAPI = koffi.load('PlanCADAPI.dll');

// Use dummy int for the first two native Java parameters (env and obj)
const OpenCommunication = PlanCADAPI.func('int Java_PlanCad_PlanCadApi_c_1OpenCommunication(int, int)');
const ShowHideWindow = PlanCADAPI.func('int Java_PlanCad_PlanCadApi_c_1ShowHideWindow(int, int, bool)');

console.log("Init communication");
let connectionResult = OpenCommunication(0, 0);
setTimeout(function() {
    checkConnection();
}, 2000);

function checkConnection() {
    if (connectionResult == '0') {
        console.log("Comunication open");
        console.log("Opening the windows. Payload should be ShowWindow and not HidenWindow");
        console.log(ShowHideWindow(0, 0, true));
    } else {
        setTimeout(function() {
            if (connectionResult == 5) {
                console.log("Connection error. Please restart app");
            } else {
                checkConnection();
            }
        }, 2000);
    }
}
