### ISSUE TITLE
%1 不是有效的 Win32 应用程序

### ISSUE THREAD

**Issue by et-hh** [Koromix/koffi#76]
@Koromix i have the problem
<img width="300" src="https://github.com/Koromix/koffi/assets/11864722/6559208b-0d31-41b5-b92e-ae9a4bf6556b" />

i use vlc.dll with koffi in electron

> "electron": "17.4.11"
> "koffi": "^2.5.20"

vlc.dll is from http://download.videolan.org/pub/videolan/vlc/3.0.18/win32/
<img width="300" src="https://github.com/Koromix/koffi/assets/11864722/dec746a4-9436-4f3e-a0e4-91451fa253f8" />

could you help me please

demo can get from https://github.com/et-hh/testvlc.git

**Comment by Koromix** [comment]
I'm pretty sure you're using Node 64-bit, while this VLC dll is 32-bit.

You can find 64-bit builds of VLC here: https://download.videolan.org/pub/videolan/vlc/3.0.18/win64/
Or use Node 32-bit, it would work too.

**Comment by zhouJiecode** [comment]
![image](https://github.com/Koromix/koffi/assets/11864722/28a3863c-6570-44e2-8ad9-9f6f9bea3d03)

my node is 32-bit...

**Comment by Koromix** [comment]
Could you try with Koffi 2.5.21-beta.1?
Install with `npm install koffi@beta`.

**Comment by jerem-guy** [comment]
Same here on win10, except that my error is in French not Chinese :) What can be the reason ? Incompatibility issue between OS / hardware and library, corrupted library, ... ?

**Comment by Koromix** [comment]
Bit late, but I changed the loading code some time ago in Koffi 2.6.9.

Does this fix this problem?

**Comment by Koromix** [comment]
Closing this issue, because it might be fixed.
Don't hesitate to comment if that's not the case.
