### ISSUE TITLE
[feat] Add a version without path of node directly listed

### ISSUE THREAD

**Issue by neko-para** [Koromix/koffi#78]
Vite tries to parse the *.node as js,which need a plugin to deal with it. I've tried vite-plugin-native, but that doesn't work well. Thus, I suggest adding a copy of index.js with that try-catch block commented.
I mean, sth. like this:
```typescript
import koffi from 'koffi/indirect'
```

**Comment by Koromix** [comment]
Could you expand a bit, and maybe point me to a project with Vite and Koffi that has problems? I don't know the first thing about Vite

**Comment by neko-para** [comment]
Vite is a tool similar to webpack but targetting on the modern browsers. The problem is that vite doesn't have any builtin support for format other than js, so it must load some plugins to support .css, .jsx, and .node. There is a plugin named vite-plugin-native, but it doesn't work.
So, because every .node file is listed inside index.js, vite (or rollup, used by vite) will try to load and parse it, and failed.
Please refer to this repo: [MaaXNext](https://github.com/neko-para/MaaXNext.git)
It is a electron app using vite. The package loader, used by package main, uses koffi.
Currently, I use patch-package to comment those require to make it work. You can repoduce the problem by:
1. `npm i`
2. uncomment those require statements in `node_modules/koffi/src/index.js`
3. `npm run dev`

**Comment by neko-para** [comment]
yes, esbuild works quite well.
Actually, there IS a problem about esbuild. With the copy loader, it will by default rename all chunk with hash. This almost prevent me from removing unused binary (like some rare arch). It does have an option to disable the rename, but as all .node have the same name `koffi.node`, it still leads to problem.

**Comment by neko-para** [comment]
There may be a better solution. I've also start an issue at the plugin's repo. Generally I believe that plugin would be the best solution, but it is quite young and buggy.

**Comment by Xutaotaotao** [comment]
> Vite tries to parse the *.node as js,which need a plugin to deal with it. I've tried vite-plugin-native, but that doesn't work well. Thus, I suggest adding a copy of index.js with that try-catch block commented. I mean, sth. like this:
> 
> ```ts
> import koffi from 'koffi/indirect'
> ```

I have the same problem, look this : [https://github.com/Koromix/koffi/issues/89](https://github.com/Koromix/koffi/issues/89)

[https://github.com/Xutaotaotao/electron-prokit](https://github.com/Xutaotaotao/electron-prokit)

**Comment by Koromix** [comment]
You can use `require('koffi/indirect')` in Koffi 2.6.2 ;)

**Comment by 1234567845246** [comment]
> `require('koffi/indirect')`您可以在 Koffi 2.6.2 中使用；)
How to call the “koffi/indirect' package, I am currently using vite packaging is also encountered this problem
![image](https://github.com/user-attachments/assets/3eea23fd-3fea-4bea-ac2e-cdfdca9a155c)
