### ISSUE TITLE
Crash on koffi.decode

### ISSUE THREAD

**Issue by neko-para** [Koromix/koffi#81]
Please refer to [this commit](https://github.com/neko-para/MaaJSLoader/commit/5031e99b82ccdb109bab2361bfa8ee6af4ebad74)
The corresponding cpp source is [here](https://github.com/MaaAssistantArknights/MaaFramework/blob/main/source/MaaToolKit/API/MaaToolKitAPI.cpp#L73)

---

The cpp function return a nul-terminated string, which may be nullptr. I've tried to mark it as `void*` and manually decode it. The cpp function did return an `External` object, but when I called `koffi.decode(ptr, 'const char*')`, the process exited without any error (even in inspect mode, it returned zero). However, if I just let koffi to decode it automatically, everything just works. I'm wondering if `koffi.decode` has any problem.

**Comment by Koromix** [comment]
This is caused by the fact that koffi.decode() is not user-friendly, and confusing. It will change in Koffi 3.0.
