### ISSUE TITLE
Crash when calling a function in a DLL

### ISSUE THREAD

**Issue by somanuell** [Koromix/koffi#83]
When I call the same function in a C++ project, no crash
When I call using koffi (with same call parameters) it crash in KernelBase.dll

Screenshot with Visual Studio 2022 after debug rebuild and "attach to" electron.exe before the call:
![image](https://github.com/Koromix/koffi/assets/6695774/3f39053f-b44c-468b-bd67-adc905ef08e9)
 Let me know how I can send you the DLL and the js...

**Comment by Koromix** [comment]
By mail: niels.martignene@protonmail.com :)

**Comment by somanuell** [comment]
Hi, could you point to a commit for the fix, please.
