### ISSUE TITLE
Unexpected Function value for variable, expected external or TypedArray

### ISSUE THREAD

**Issue by josepgomes** [Koromix/koffi#85]
Hi,

I'm trying to decode koffi methods responses to UTF-8. Everything runs fine without the decode step. I'm trying to follow the examples and other issues but i always get this error: Unexpected Function value for variable, expected external or TypedArray.

```js
process.on('message', ({ id, method, args = [] }: { id: number, method: keyof Saga, args: any }) => {
        try {
            const method2run = koffi.decode(instance[method], 'string');
            const res = method2run!(...args);
            const data = iconv.decode(res, 'UTF-8');
            process.send!({ id, data });
        } catch (ex: any) {
            process.send!({ id, error: ex.message });
        }
    });
```

What am I doing wrong?

**Comment by neko-para** [comment]
I don't know why you're calling a string?
```typescript
const method2run = koffi.decode(instance[method], 'string'); // method2run will be a string
const res = method2run!(...args); // wtf?
```
After all, the error means that `instance[method]` seems to be a function, while koffi.decode expect an `External` object or a TypedArray. This sounds like you're misusing `koffi.decode`.

**Comment by josepgomes** [comment]
Sorry, to simplify, now i have this:

```js
this.saga_ini = lib.stdcall('saga_ini', 'int', ['string', 'string', 'string']);
```

I want to call this.saga_ini and that everything that returns is UTF-8 encoded. Can you help me on that?

Thanks!

**Comment by Koromix** [comment]
Well, what does the C function look like?

```c
int __stdcall saga_ini(const char *what_is_this, const char *what_is_that, const char *and_this);
```

**Comment by josepgomes** [comment]
yes, but when using koffi the encoding is not right, a bunch of "<?>" in special characters. So o think i need to force it somehow to UTF-8.

**Comment by Koromix** [comment]
Koffi uses UTF-8 to encode the strings. Perhaps your API expects something else?

**Comment by josepgomes** [comment]
Even the method's output? Because input is fine!

**Comment by Koromix** [comment]
If you have a "const char *" return value or output parameter, it will be converted from UTF-8 to a JS string.

Koffi uses the V8 engine converter to do this. Perhaps your UTF-8 is not quite valid? (overlong sequences, etc.)

**Comment by Koromix** [comment]
Both do the same.
Are those strings allocated on the heap?

**Comment by josepgomes** [comment]
It's a C# compiled DLL, they are simple string declared variables, when other C# projects run it the encoding is fine, when using koffi it outputs the <?> on accents. I really don't have any more clues.

**Comment by Koromix** [comment]
Hard to know anything about it then. The C# method could be outputting Windows-1252, for example.

If you don't want to share publicly the C# code (at least the saga_view_eval method) you can send a mail to niels.martignene@protonmail.com so I can see.

**Comment by josepgomes** [comment]
Ok, after a lot of debugging the problem is overlong sequences... how can i solve this?

**Comment by neko-para** [comment]
Maybe you should use TypedArray, e.g. Uint8Array, instead of string as the output. You can use `void*` as the output type and then decode it as `uint8_t*` with `'typed'` hint.

**Comment by josepgomes** [comment]
I know that is asking for to much, but can you write me the example using this, please:

```js
this.saga_eval = lib.stdcall('saga_eval', 'string', ['string']);
```

**Comment by neko-para** [comment]
In case you got a `const char*` from c lib, which contains some overlong seq.
```javascript
// this.saga_eval = lib.stdcall('saga_eval', 'string', ['string']);
this.saga_eval = lib.stdcall('saga_eval', 'void*', ['string']);

/* --- */

const data_ptr = this.saga_eval('abc') // data_ptr will be an External
const array = koffi.decode(data_ptr, koffi.array('char', LEN, 'Typed')) // array will be an Uint8Array
// LEN above could simply got via calling strlen.
```

It's important that, you cannot directly access this string, as the string type provided by V8 doesn't support some of the character, so you can only handle it as a buffer. However, if you just need to transfer it, you even don't need to decode it, just pass that `External` to other c functions. If you really want to do sth. with it, you may search for some package to provide a full-featured string type. Those packages should allow to construct a string from an Uint8Array.

**Comment by josepgomes** [comment]
Testing this, before i change the example line "data_ptr" receives a string. After i change it to void* the "data_ptr" receives an empty object: { }. What am i missing here?

**Comment by neko-para** [comment]
@josepgomes This ’empty object {}‘ is what I've mentioned the `External`. It's opacity.

**Comment by josepgomes** [comment]
I need help knowing the LEN because data_ptr is not a string to get .length. Whats the best option to handle this?

**Comment by neko-para** [comment]
> `// LEN above could simply got via calling strlen.`

**Comment by neko-para** [comment]
your `External` IS a valid NUL-terminated string, thus using strlen could got the array size. But if you want to get the string length instead of string buffer size, you may need some manual caculation.
In this case, you may want to iterate the Uint8Array, as it could get each byte via `arr[idx]`, then you can implement a full-featured utf8 strlen.
---
In case there is a CJK char '啊‘, its string length shall be 1, while its string buffer size would be 3.

**Comment by josepgomes** [comment]
Sure, i'm trying, but how can i run strlen? I have this, but is not working.

```js
const stringh = koffi.load('string.h');
this.strlen = stringh.func('strlen', 'int', ['string']);
const len = this.strlen(EXTERNAL HERE);
```

**Comment by neko-para** [comment]
If you are on linux, then you shall load strlen from libc.so.6, which can be found via ldd.
![image](https://github.com/Koromix/koffi/assets/26452623/b3d52eb7-62f5-45b6-ad3b-01c0f312964a)

---

If you are on windows, then you shall load it from msvcrt.dll, which can be found in C:\Windows\System32
![image](https://github.com/Koromix/koffi/assets/26452623/7f66e766-f24b-4180-b569-3f8c1fc7e78f)

---

Generally, these library will always linked with your program, so you can just use `koffi.load('libc.so')` or `koffi.load('msvcrt.dll')`

**Comment by josepgomes** [comment]
So, i'm stuck in the some problem: TypeError: Unexpected Object value, expected string. Error in the last line, while trying to strlen.

```js
const lib = koffi.load('saga.dll');
const saga_eval = lib.stdcall('saga_eval', 'void*', ['string']);
const data_ptr = saga_eval('abc')
const stringh = koffi.load('msvcrt.dll');
const strlen = stringh.func('strlen', 'int', ['string']);
const len = strlen(data_ptr);
```

**Comment by neko-para** [comment]
As the data_ptr is `External`, you should type `strlen` as `const strlen = stringh.func('strlen', 'int', ['void*']);`, just like `sega_eval` above.

**Comment by josepgomes** [comment]
So this is my current code and it's working! The only problem i have is that converting the array always lead to the same encoding problem with <?>. Is there any solution for the overlong sequences in utf-8?

```js
    const value = this.saga_eval_raw(...args);
    const stringh = koffi.load('msvcrt.dll');
    const strlen = stringh.func('strlen', 'int', ['void*']);
    const len = strlen(value);

    if (len < 1) {
      return "";
    }

    const array = koffi.decode(value, koffi.array('char', len, 'Typed'));
    return iconv.decode(array, 'UTF-8');
```

**Comment by neko-para** [comment]
> The only problem i have is that converting the array always lead to the same encoding problem with <?>.

Of course, as the problem is that the native string from V8 cannot store those sequences. Unless V8 decide to fix it, no method could make that work. You should treat that array as a opaque buffer instead of string, and transfer it to other function that support it (via ffi).

If you DO want to process it as string, you should find a package that soft emulate a string (maybe provide you a `FullFeaturedString` class and some utils to deal with it).

**Comment by neko-para** [comment]
Actually, I'm not sure if there IS a restriction on V8 string. The problem could occur for two reasons. Despite the reason we talk above, it may also caused by the converter (both native and iconv, as iconv may use native converter). You can test it by manually construct a string contains overlong sequences, like `'\xaa\xbb\xcc...'`(actually I don't know how to encode it, you can print that overlong char, which should be a sequence of 0xF*), and see if V8 would raise an error when parsing it. If no problem raised, then you can seek for a decoder that support overlong sequence utf8

**Comment by josepgomes** [comment]
Well i solved in this way, for future reference:

```js
   const array = koffi.decode(value, koffi.array('char', len, 'Typed'));
    const decoder = new TextDecoder('iso-8859-2', { fatal: false, ignoreBOM: true });
    return decoder.decode(array);
```

**Comment by neko-para** [comment]
According to your solution, is that string (from c function) come from a file? As you tried to decoded it as latin-2, which is MBCS but not unicode. It seems that the problem is that you've tried to decode a non-utf8 data into string, which actually isn't much related to ffi.

**Comment by neko-para** [comment]
Meanwhile, as you set that `ignoreBOM`, the problem may also caused by BOM in string (which usually at the beginning of a file on Windows). The BOM of utf8 is 0xFEFF, which isn't a valid sequence in normal utf8 string. You can print out and see if that data is starting with it. If so, you can slice that Uint8Array and then simply convert into string.
