### ISSUE TITLE
If only proc address, no method name

### ISSUE THREAD

**Issue by geekgray** [Koromix/koffi#88]
How to use __Out__
I can't use name，only use **Proc Address**
I want to get the string

buffer no change
``` 
// typedef void (*_HWi32_GetSensorName)( int iSensor, char* sensor_desc_buf, int sensor_desc_buf_sz );

const GetSensorName = lib.func(687, "void", ["int", "uint64_t *", "int"]);
// const GetSensorName = lib.func(687, "void", ["int","__Out__ uint64_t *","int"]);   // ERROR Unknown or invalid type name '__Out__ uint64_t *'  

let buf = Buffer.allocUnsafe(256);
console.log("GetSensorName", GetSensorName(3, buf, buf.length));
```
How to proceed, please, thank you！

**Comment by Koromix** [comment]
In Koffi 2.6.0 and earlier versions, the string qualifiers (_Out_, _In_, etc.) only work when using [prototype-like definitions](https://koffi.dev/functions#c-like-prototypes).

I've changed this in Koffi 2.6.1, which I've just released, so your code should almost work. But it's `_Out_`, not `__Out__`.

So for Koffi 2.6.0 and earlier, use this:

```js
// typedef void (*_HWi32_GetSensorName)( int iSensor, char* sensor_desc_buf, int sensor_desc_buf_sz );

const GetSensorName = lib.func(687, "void", ["int", koffi.out("uint64_t *"), "int"]);

let buf = Buffer.allocUnsafe(256);
console.log("GetSensorName", GetSensorName(3, buf, buf.length));
```

And for Koffi 2.6.1, this should work too:

```js
// typedef void (*_HWi32_GetSensorName)( int iSensor, char* sensor_desc_buf, int sensor_desc_buf_sz );

const GetSensorName = lib.func(687, "void", ["int", "_Out_ uint64_t *", "int"]);

let buf = Buffer.allocUnsafe(256);
console.log("GetSensorName", GetSensorName(3, buf, buf.length));
```

**Comment by geekgray** [comment]
Upgrade 2.6.1 is OK！
But buffer have no change. 
The dll is already in production, so there is no problem
What could be the cause?
So how do I find the problem

**Comment by geekgray** [comment]
Okay, I upgrade 2.6.1. that solves my confusion. Thank you
