### ISSUE TITLE
How to declare an empty structure

### ISSUE THREAD

**Issue by oopses** [Koromix/koffi#90]
I have an empty um structure used in a union

`export const test1= koffi.struct('test2', {
  data: koffi.union({
    t2: test, 
  })
})
`
If used directly

`koffi.struct('test',{})`

the error:
 **is not allowed in C**

**Comment by oopses** [comment]
I looked at the source code and it was disabled by this commit.

https://github.com/Koromix/rygel/commit/c5a14b6a813f76b358810b04a81c0593a4757240

There is an empty structure in the union defined by the dll I am using. Is there any other way to define it? Or I can fork it separately and handle it.

**Comment by Koromix** [comment]
Empty structs are not allowed in C (although GCC accepts them). From what I can see, the various ABIs are ambiguous about 0-sized objects.

However, C++ allows empty structs but defines as 1-byte sized.

Anyway, what is the purpose of this empty struct? Can't you just skip it?

**Comment by oopses** [comment]
> Empty structs are not allowed in C (although GCC accepts them). From what I can see, the various ABIs are ambiguous about 0-sized objects.
> 
> However, C++ allows empty structs but defines them as 1-byte sized, as if it was `struct { char __dummy; }` or something like that.
> 
> Anyway, what is the purpose of this empty struct? Can't you just skip it?

Thanks for the reply. I contacted the sdk provider to take care of it. I am currently studying the source code of koffi, which is very helpful to me.
