### ISSUE TITLE
Segmentation fault on what should be ok?

### ISSUE THREAD

**Issue by lf94** [Koromix/koffi#92]
I've been banging my head on this one for awhile now.

I'm trying to call these two functions:

https://github.com/libfive/libfive/blob/master/libfive/src/libfive.cpp#L191
https://github.com/libfive/libfive/blob/master/libfive/src/libfive.cpp#L306

As you see, one returns a libfive_tree and the other takes a libfive_tree. Passing the optimized into the mesher causes a segmentation fault...

Another oddity is calling render_mesh twice, one after the other, also causes a segmentation fault.

I'm completely confused :D.

Thanks again as always!

**Comment by Koromix** [comment]
Can you send the JS code used to do this?
With the type definitions and the calls.

**Comment by lf94** [comment]
Sorry for such a late response. It's been a crazy week.

So I think the issue may stem from libfive being multi-threaded.

How does koffi handle these types of libraries?

In regards to reproducing, check out https://github.com/lf94/summonscript. The bindings are in libfive.js. You can try a very simple example that lives in examples/repeat.js. I find it very weird, as this example fails, but there are more complex examples that succeed.

Please let me know if you need anything else!

**Comment by lf94** [comment]
You're probably going to want to check out utils/preview.js too.

**Comment by lf94** [comment]
Hey @Koromix , anything on this question?

> So I think the issue may stem from libfive being multi-threaded.
> How does koffi handle these types of libraries?

I'm trying to think of the smallest possible reproduction. Really it seems to manifest when calling anything twice with the same reference...

**Comment by lf94** [comment]
I think I'm getting to the bottom of it, the problem **must** be manifesting on the libfive side and can't possibly be the fault of _two_ FFI libraries. https://github.com/libfive/libfive/issues/552

**Comment by Koromix** [comment]
I did try but got "connect ENOENT /tmp/libfive_mesh.sock" error, did I do something wrong?
I'm running Ubuntu 22.04 and installed libfive with APT.

**Comment by lf94** [comment]
You need to start the viewer; honestly it's ok, as I've contributed a single threaded call to libfive to fix this issue over there :)

Thanks for trying!
