### ISSUE TITLE
Registered callback not working (Type cannot be used as a parameter)

### ISSUE THREAD

**Issue by josepgomes** [Koromix/koffi#93]
C code
```c
typedef char * (__stdcall *CallbackReqInputType) (char *title, char *prompt, char *strini);
static CallbackReqInputType CallbackReqInput = NULL;

_decIspec(dilexport) void __stdcall SagaRegCalbackReqInput (CallbackReqInputType func) {
    CallbackReqInput = func;
}
```
JS Code
```js
const CallbackReqInputType = koffi.proto('char* CallbackReqInputType (char *title, char *prompt, char *strini)');
const SagaRegCalbackReqInput = this.lib.stdcall('void SagaRegCalbackReqInput (CallbackReqInputType func)');

const cb1 = koffi.register((title: string, prompt: string, strini: string) => {
  return `yes`;
}, koffi.pointer(CallbackReqInputType));

SagaRegCalbackReqInput(cb1);
```

Generates an error: Type CallbackReqInputType cannot be used as a parameter.

EDIT:

If i use struct method:

```js
const CallbackReqInputType = koffi.struct('char * (__stdcall *CallbackReqInputType)', { title: 'char *', prompt: 'char *', strini: 'char *' })
```

Generates an error: Unknown or invalid type name 'CallbackReqInputType'

**Comment by josepgomes** [comment]
@Koromix @neko-para any hints?

**Comment by josepgomes** [comment]
In the docs it saiys to make it a pointer:

```js
void SagaRegCallbackReqSeltxt (CallbackSeltxtType* func)
```

But when i return inside the registed callback, for example, the value 1 the application crashes without any error. Do i need to convert the return value for something that C understands?

**Comment by neko-para** [comment]
Your returned value should match the type you define previously.

Meanwhile, I suggest you to add a infinite eventloop, like `setTimeout(() => {}, 1000 * 3600)`, to prevent node exit. The register callback won't prevent node from quitting, and I've met this problem many times. it will likely cause some strange error.

**Comment by neko-para** [comment]
Also, node have a command line option, which can print the native exception instead of just crash

**Comment by oopses** [comment]
```
const CallbackReqInputType = koffi.proto('char CallbackReqInputType (char *title, char *prompt, char *strini)');
const SagaRegCalbackReqInput = this.lib.stdcall('void SagaRegCalbackReqInput (CallbackReqInputType func)');

const cb1 = koffi.register((title: string, prompt: string, strini: string) => {
  return `yes`;
}, koffi.pointer(CallbackReqInputType));

SagaRegCalbackReqInput(cb1);
```

**Comment by josepgomes** [comment]
Yes, i always return the value with the same type defined in the callback. I will test later your hint to see if i can get an error that tells me something! Thanks!

**Comment by josepgomes** [comment]
@neko-para my DLL is in 32 bit, is this a problem for register callbacks? I cannot find anything else wrong, when returning the callback result the node.js just crashes without any error.

**Comment by Koromix** [comment]
On x86 32-bit it is extremely important to get the convention right for callbacks or it will crash. It works regardless for normal calls but nor for callbacks.

You define CallbackReqInputType as __stdcall in C but not in JS.

Try it like this:

```
const CallbackReqInputType = koffi.proto('char __stdcall CallbackReqInputType (char *title, char *prompt, char *strini)');
const SagaRegCalbackReqInput = this.lib.stdcall('void SagaRegCalbackReqInput (CallbackReqInputType func)');

const cb1 = koffi.register((title: string, prompt: string, strini: string) => {
  return `yes`;
}, koffi.pointer(CallbackReqInputType));

SagaRegCalbackReqInput(cb1);
```

**Comment by josepgomes** [comment]
Well, IT WORKS! ❤️

**Comment by josepgomes** [comment]
Sorry to reopen this issue but my callback computation in JS needs to be async. In the old c# project we just pause the thread and resume it and for the DLL it's all synchronous (using semaphores). In JS we have async and await, but it makes the method asynchronous and the DLL method is not waiting for the callback to end because in C it is a sync method. Do we have any solution for this? Thanks in advance!

**Comment by josepgomes** [comment]
Example code:

```js
const CallbackReqInput = koffi.register(async (title: string, prompt: string, strini: string) => {
      do {
        await new Promise((resolve) => setTimeout(resolve, 50));
      } while (!this.inputResponse);

      return this.inputResponse;
}, koffi.pointer(this.CallbackReqInputType));
```

**Comment by neko-para** [comment]
You should pass a function pointer from C to JS, and when JS callback finishs its work, use that callback to return data. But I'm not sure if koffi.decode would accept the callback type, thus exposing another function from C would be a workaround.

**Comment by josepgomes** [comment]
What you explain was this?

```c
void performCalculation(int value, Callback callback) {
    // Perform some calculation
    int result = value * 2;

    // Call the callback to return the result to JavaScript
    callback(result);
}
```

Is there any workaround without change the C code?

**Comment by neko-para** [comment]
Actually I mean that your JS function call a callback pass from C to give data to C, but, after all, the logic are the same.

---

Yes, at least now it seems that koffi doesn't support  *await* the `Promise` returned from js during calling the callback from C. I've raised an issue about it. #87

**Comment by Koromix** [comment]
I'm keeping issue #87 open for async callbacks (if at all possible), so I'm closing this one.
