### ISSUE TITLE
When I call the load method, it prompts me that the specified module cannot be found.

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [Koromix/koffi#95]
```js
const koffi  = require('koffi')
const path = require('path')
const dir = path.join(__dirname, 'add.dll');
// console.log(dir)
const lib = koffi.load(dir); // or so './add.ll'
const addFun = lib.stdcall('funAdd', 'int', ['int', 'int']);
const generate_uuid = lib.stdcall('generate_uuid', 'string', []);
console.log(generate_uuid())
```
I don’t understand. I feel that my address is correct, but it always prompts an error message that the module cannot be found, which makes me very distressed.
This is my directory structure。
![image](https://github.com/Koromix/koffi/assets/30976418/18ab6ae2-b2a8-4e86-ace2-e4a05a404088)
my environment：
node  v14.19.0
win11 23H2 

Thank you very much for developing this library. It is really convenient. There is no need to install other dependencies, such as the py environment of node-ffi.

**Comment by xiaoxiaohuayu** [comment]
> 当无法加载 DLL 时，Windows 倾向于在所有情况下都给出相同的一般错误消息。
> 
> 也许它找不到它...或者它可能找不到这个依赖的另一个 DLL。或者 Node 是 32 位的，DLL 是 64 位的（反之亦然）。
> 
> 使用 https://github.com/lucasg/Dependencies（DependenciesGui.exe）来分析您的DLL，并查看它是否依赖于计算机中缺少的某些内容。
Thank you very much for your prompt reply to my message, it was of great help to me. I will try to analyze and solve it.

**Comment by Koromix** [comment]
Feel free to reopen or open another issue is the problem persists ;)
