### ISSUE TITLE
Error loading DLL, unable to find the specified module

### ISSUE THREAD

**Issue by lightzero** [Koromix/koffi#97]
Other DLLs required by the DLL are already in the same file directory.
ERR:unhandledRejectionError: Failed to load shared library:The specified module could not be found

**Comment by jerem-guy** [comment]
I have the same error with `koffi.load`.
Can it be linked to a corrupted DLL ? I have all the DLLs in my folder but for some reason it fails for one of them.
Or can it be related to path containing special characters ? Some user names has accents or dash in their names for example

**Comment by Koromix** [comment]
Can you try with Koffi 2.6.9 or Koffi 2.6.10 and report to me if it works better?

**Comment by Koromix** [comment]
Closing this issue, because it might fixed.
Don't hesitate to comment if that's not the case.
