### ISSUE TITLE
Failed to install koffi@2.6.2

### ISSUE THREAD

**Issue by Howlcn1997** [Koromix/koffi#98]
**OS:**
Windows 11
**Node**
16.20.1

When installing koffi version 2.6.2, the installation failed, because `Failed to load prebuilt binary, rebuilding from source` 
`$ npm i koffi@2.6.2
npm ERR! code 1
npm ERR! path node_modules\koffi
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node src/cnoke/cnoke.js -p . -d src/koffi --prebuild
npm ERR! Failed to load prebuilt binary, rebuilding from source
npm ERR! Error: CMake does not seem to be available
npm ERR!     at check_cmake (node_modules\koffi\src\cnoke\src\builder.js:398:27)
npm ERR!     at Builder.build node_modules\koffi\src\cnoke\src\builder.js:232:9)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm ERR!     at async main (node_modules\koffi\src\cnoke\cnoke.js:145:9)`

but when installing 2.6.1, the installation was successful.

**Comment by Koromix** [comment]
Indeed... shame on me, it's not the first time I break prebuilds.

I have finally added a check in the release script to prevent that from happening again. And released Koffi 2.6.3.

Thanks for notifying me :)
